### ISSUE TITLE
no watch is triggered when observed is set with same value

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#10]
hi @David-Desmaisons 

notice that the view is not updated with last data if the data values are unchanged. my case, i have different tabs and when going from a tab without webframe to a tab with webframe although the getters are called from the neutronium application the watch code is not.

ive try manually changing a variable to same value and the watch does not trigger either.

this results in the web view not having the last values from the model when we swap the tabs

is this by design, how to workaround the issue?

thanks and regards

jorge costa

**Comment by David-Desmaisons** [comment]
1) If you update a view model attribute with a value equal to the previous one (Object.Equals(.....)) then no chnages are trigerred in the javascript session as a performance optimization. 

2) I am mot sure of the scenario you are trying to solve and why feature 1) is a problem for your scenario. Could you give more details so we can think about some work-around?

**Comment by jmecosta** [comment]
this is a problem because of the tabs, and also for example with remote desktop connection. with the rdp i left me webview with my d3 diagram. at home i connect via rdp and the diagram is gone. 

the tabs it happens the same thing, it shows only when the tab with webview is show, after changing tabs it disapear. Ive made this workaround:

```
        public void OnSelectedViewChanged()
        {
            if (this.SelectedView != this.BuildModel)
            {
                this.BuildModel.WebFrame.CurrentNodeData = string.Empty;
            }
            else
            {
                ThreadPool.QueueUserWorkItem(this.UpdateDataWithDelay, null);
            }
        }

private void UpdateDataWithDelay(object state)
        {
            Thread.Sleep(1000);
            this.BuildModel.WebFrame.CurrentNodeData = this.BuildModel.CurrentBuildData + " ";
        }
```

please note the " " in the end, it was the only way i could get the diagram to show again after switching the tabs. the rdp its still a problem

**Comment by David-Desmaisons** [comment]
Hi @jmecosta , happy you got a workaround. That said I am still unclear about you scenario.  It seens that something worng is going with the life cycle of your wpf elements, but I am unclear which without seeing your code.

If you re-create the tab-component, if you applied the binding with the correct view-model each time, you should not need extra work.

But once again, it is difficult to give recomendation without seeing the complete code.

**Comment by jmecosta** [comment]
@David-Desmaisons ive tried to replicate this in the same sample i sent earlier but there the values remain in view after swapping tabs.  so not sure whats going on with my application, do you have any idea how could the data in the view not be loaded from the model? maybe some synchronization issue?

**Comment by David-Desmaisons** [comment]
Hello @jmecosta , the only case known to me were property changes has no effect is when old and new value are the same using Object.Equals...

If you experimenting a problem besides, this use case please check application trace that contains information in case of error binding. Ideally you should isolate the minimal scenario to reproduce the issue so that I can investigate.

**Comment by David-Desmaisons** [comment]
Jello @jmecosta , any news on this one?

**Comment by jmecosta** [comment]
I haven't had time to investigate further, I will likely try again
tomorrow.

**Comment by jmecosta** [comment]
@David-Desmaisons not sure whats going on, ive tried with a simple string and i can see values returned to the view after changing tab. 

however the same does not happen if i put my data, of type

```
<?xml version="1.0" encoding="utf-8"?>  
<DirectedGraph Title="DrivingTest" Background="Blue" xmlns="http://schemas.microsoft.com/vs/2009/dgml">  
   <Nodes>  
      ...  
   </Nodes>  
   <Links>  
      ...  
   </Links>  
   <Categories>  
      ...  
   </Categories>  
   <Properties>  
      ...  
   </Properties>  
</DirectedGraph> 
```

the data is that copied in to the string property is 8k characters. Ive tried with dummy string "======" of 10k chars and it works

so looks like its related with the format of the string? or size?

if you have no ideas whats going on then please close this ticket, to all data except for mine it works fine

**Comment by David-Desmaisons** [comment]
@jmecosta , for now I am closing this. If you have a set of data for which you can reproduce the problem please open another issue.

**Comment by jmecosta** [comment]
@David-Desmaisons i made a video of the reproducer. The issue occurs for all my neutronium views. Closing a RDP windows and opening it again causes the all view to disappear. If u have tabs, the data is redraw so kind of works. notice also sometimes while open RDP cef just crashes. Not sure if this helps u in any way.
[20190706_140033.zip](https://github.com/NeutroniumCore/Neutronium/files/3364627/20190706_140033.zip)
