### ISSUE TITLE
Logging on JS side

### ISSUE THREAD

**Issue by genyx** [NeutroniumCore/Neutronium#100]
I need custom logging on JS side.

Since we use NLog on C# side, the ideal solution may be [JSNLog](http://jsnlog.com/) to give the JS log messages to c# to log. But i dont know where to set up JSNLog's [configuration](https://github.com/mperdeck/jsnlogSimpleWorkingDemos/blob/master/jsnlogSimpleWorkingDemos/JSNLogDemo_NLog/Views/Home/Index.cshtml#L12) or header scripts.

Since this is a fairly general topic, i ask here for solution attempts.

**Comment by David-Desmaisons** [comment]
You should not need this library.
You can implement a [IWebSessionLogger](https://neutroniumcore.github.io/Neutronium/articles/debug.html#trace) where the logging will be provided by your C# loggin library of choice.
If you need only logging from javascript console only implement the LogBrowser method.
Then just call:
```
ar myLogger = new MyLogger();
HTMLEngineFactory.Engine.WebSessionLogger = myLogger;
````.

**Comment by genyx** [comment]
Ok, i will try.

Quick question: from IWebSessionLogger:
`void WebBrowserError(Exception exception, Action cancel);`
What does the "cancel" Action do?

**Comment by David-Desmaisons** [comment]
In awesomium, it was possible to try to cancel the closing of a browser,  so it was also exposed in Neutronium. For more modern browser througth this will have no effect.
