### ISSUE TITLE
Cannot build/run Neutronium apps

### ISSUE THREAD

**Issue by brianjlacy** [NeutroniumCore/Neutronium#104]
Whether I download the SPA Demo app, or create a new project from the Visual Studio SPA template, I can't build or run the app. Here's what happens:

    C:\{ProjectDir}> npm install
    C:\{ProjectDir}> npm run dev
    npm ERR! path C:\{ProjectDir}\package.json
	npm ERR! code ENOENT
	npm ERR! errno -4058
	npm ERR! syscall open
	npm ERR! enoent ENOENT: no such file or directory, open 'C:\{ProjectDir}\package.json'
	npm ERR! enoent This is related to npm not being able to find a file.
	npm ERR! enoent

	npm ERR! A complete log of this run can be found in:
	npm ERR!     C:\Users\{winuser}\AppData\Roaming\npm-cache\_logs\2019-02-01T19_29_41_022Z-debug.log

The error log:

	0 info it worked if it ends with ok
	1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
	1 verbose cli   'C:\\Users\\{WinUser}\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
	1 verbose cli   'run',
	1 verbose cli   'dev' ]
	2 info using npm@6.7.0
	3 info using node@v10.13.0
	4 verbose stack Error: ENOENT: no such file or directory, open 'C:\SRC\Neutronium.SPA.Demo\package.json'
	5 verbose cwd C:\SRC\Neutronium.SPA.Demo
	6 verbose Windows_NT 10.0.16299
	7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\{WinUser}\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
	8 verbose node v10.13.0
	9 verbose npm  v6.7.0
	10 error path C:\SRC\Neutronium.SPA.Demo\package.json
	11 error code ENOENT
	12 error errno -4058
	13 error syscall open
	14 error enoent ENOENT: no such file or directory, open 'C:\SRC\Neutronium.SPA.Demo\package.json'
	15 error enoent This is related to npm not being able to find a file.
	16 verbose exit [ -4058, true ]

I'm using:
* npm 6.7.0
* .NET Framework 4.7.2
* Visual Studio 2017

I also noticed there indeed does not appear to be a `package.json` in these applications..

**Comment by David-Desmaisons** [comment]
`package.json` file is under the View directory. C:\SRC\Neutronium.SPA.Demo\View in your case.
