### ISSUE TITLE
Add support for Notify collection changes with multiple items

### ISSUE THREAD

**Issue by vmartos** [NeutroniumCore/Neutronium#105]
Hello,

First of all, congratulations for this amazing javascript<->C# bridge framework

We are starting to use neutronium in order to display some views in our app using Vue.js. We have ViewModels that contains a property of type ObservableRangeCollection, similar to this:
https://gist.github.com/weitzhandler/65ac9113e31d12e697cb58cd92601091

when we Use the AddRange and RemoveRange to add/remove multiple elements, but with just one collection changed event, we see that Neutronium bindings just updates one element.
I see that the problem is here: https://github.com/NeutroniumCore/Neutronium/blob/master/Neutronium.Core/Binding/Updaters/CollectionJavascriptUpdater.cs#L39 just manages one element at a time even if the NewItems, or OldItems contains more than one element.

We have modified our ObservableRangeCollection to send multiple events one for each change.
if we have time we can change it and open a pull request with the needed changes on order to support multiple elements in collection changes.

Thank you

**Comment by David-Desmaisons** [comment]
Hello @vmartos , thanks for your words.
PRs are always welcome. That said in that case I may ba abble to take a look in a short time. I will let you know.

**Comment by David-Desmaisons** [comment]
It is delivered in version 1.5.2. The other good news is that Neutronium implementation of range updates are optimized compared individual  updates.

**Comment by vmartos** [comment]
@David-Desmaisons That was fast! I'll update to the last version. Thank you for your work!
