### ISSUE TITLE
Access CfxOnDraggableRegionsChangedEventHandler  

### ISSUE THREAD

**Issue by costs** [NeutroniumCore/Neutronium#11]
[Frameless window] I think  event CfxOnDraggableRegionsChangedEventHandler OnDraggableRegionsChanged  Event Binding ,Can you help me?
,Thank you

**Comment by David-Desmaisons** [comment]
You measn that you want o hook to listen to the CfxOnDraggableRegionsChangedEventHandler OnDraggableRegionsChanged  event, is that correct?

**Comment by costs** [comment]
Is such that.

**Comment by costs** [comment]
Eureka ,  namespace Tests.ChromiumFX.Infra.Helper  

;Thank you

**Comment by David-Desmaisons** [comment]
Hello @costs , I will investigate a bit more this issue in order to expose low level access to Cfx API

**Comment by costs** [comment]
hello @David-Desmaisons , I do not quite understand how to ;
 eg: use[https://github.com/NeutroniumCore/NeutoniumDemo/blob/master/NeutoniumDemo/MainWindow.xaml](url)   Is  HtmlView     hook to listen to the    Event binding , How to access ChromiumFxWpfWindow ChromiumWebBrowser ?

**Comment by David-Desmaisons** [comment]
@costs , 

Now Neutronium control have a `WPFWebWindow` property returning an `IWPFWebWindow` instance.  When working with ChromiumFx, it is possible to cast this interface to a `IWPFCfxWebWindow` which provides full access to ChromiumFx browser API

```C#
 public interface IWPFCfxWebWindow : IWPFWebWindow
{
   ChromiumWebBrowser ChromiumWebBrowser { get; }
}
```

Usage:
```C#
private void Window_Loaded(object sender, RoutedEventArgs e)
 {
      wcBrowser.OnDisplay += WcBrowser_OnDisplay;        
 }

  private void WcBrowser_OnDisplay(object sender, Neutronium.Core.Navigation.DisplayEvent e)
  {
      var windowCfx = wcBrowser.WPFWebWindow as IWPFCfxWebWindow;
       windowCfx.ChromiumWebBrowser.DragHandler.OnDragEnter += DragHandler_OnDragEnter;
  }

  private void DragHandler_OnDragEnter(object sender, Chromium.Event.CfxOnDragEnterEventArgs e)
  {
       Trace.WriteLine("OnDragEnter fired");
  }
```

Note that `WPFWebWindow` property will be null on loading and may change when navigating. Using OnDisplay event to capture the current value is thus strongly recommended.

[Example here](https://github.com/NeutroniumCore/Neutronium/blob/master/Examples/Example.ChromiumFX.Vue.SOP/MainWindow.xaml.cs)

**Comment by David-Desmaisons** [comment]
This issue will be closed in next release of Neutronium

**Comment by costs** [comment]
@David-Desmaisons   
Okay,   I want to implement borderless window with drag logic on some HTML element. I found some working examples (like[ frameless window for 

- Chrome]([https://chrome.google.com/webstore/detail/frameless-window-sample/hjjdaddngnaofnfjpajdcbdmkegiakec](url)))

 and this is what I've tried:

 `.title-area 
{
   -webkit-app-region: drag;
}

<div class='title-area'>
    A draggable area
</div>`

c#
` windowCfx.ChromiumWebBrowser.DragHandler.OnDraggableRegionsChanged += DragHandler_OnDraggableRegionsChanged;
       private Region draggableRegion = null;
        private void DragHandler_OnDraggableRegionsChanged(object sender, Chromium.Event.CfxOnDraggableRegionsChangedEventArgs args)
        {
 System.Windows.Application.Current.Dispatcher.Invoke(delegate
            {
                var regions = args.Regions;
               if (regions.Length > 0)
                {
                    foreach (var region in regions)
                    {
                        var rect = new System.Drawing.Rectangle(region.Bounds.X, region.Bounds.Y, region.Bounds.Width, region.Bounds.Height);

                        if (draggableRegion == null)
                        {
                            draggableRegion = new Region(rect);
                        }
                        else
                        {
                            if (region.Draggable)
                            {
                                draggableRegion.Union(rect);
                            }
                            else
                            {
                                draggableRegion.Exclude(rect);
                            }
                        }
                    }
                }
            });

        }

           
`
It does not work.
thank you for your help.

**Comment by David-Desmaisons** [comment]
@costs , could you create a github repository with this implementation so it will be easier for me to investigate and also will be a good example for people with similar needs.

**Comment by costs** [comment]
@David-Desmaisons   like [ https://github.com/costs/Dragable-borderless-window-in-chromiumfx](url)

**Comment by David-Desmaisons** [comment]
Hi @costs , I just took a look at your repo.
Rigth now it can not work as you are referecing the last version which doe not include this improvement.
I will let you know when version with these changes will be released,

**Comment by costs** [comment]
@David-Desmaisons 

Thank you very much if you can let know when the new version released. May I ask about when it will be released?

**Comment by David-Desmaisons** [comment]
@costs It should be released this month.

**Comment by costs** [comment]
Hi @David-Desmaisons ,
Messy code will happen when I use chromiunFX.Use CefSharp the situation is norman, and the Draggable region can be realized.  CefSharp compatibility is better, I hpoe you can add CefSharp WebBrowserEngine function.

**Comment by David-Desmaisons** [comment]
@costs , what kind of scenario are broken with ChromiumFx?
I never found any significant issue with ChromiumFx, and small issue were rapidly corrected by maintener.

**Comment by costs** [comment]
@David-Desmaisons   This  My project : [https://github.com/costs/MyDemo](url)   ; Chinese garbled

**Comment by David-Desmaisons** [comment]
Vresion 0.4.0 published with the fix for this issue

**Comment by David-Desmaisons** [comment]
@cost, I will take a look at your project later this wek

**Comment by David-Desmaisons** [comment]
Hi @costs , I made some tweaks on your project (such as adding nuget reference, adding correct main window in app), and it is loading correctly now.
You will have to improve your HTML to use correctly the viewmodel , but I was not abble to detect any problem with ChromiumFx.

**Comment by David-Desmaisons** [comment]
@costs See my fork of you project

**Comment by David-Desmaisons** [comment]
@costs , I am working in a out-of-the-box support for `-webkit-app-region: drag;` regions. This means that region having these CSS property will automatically allow drag of the Neutronium application without any extra code.
This should be ready soon and available in next Neutronium version.

**Comment by David-Desmaisons** [comment]
[Here is the documentation](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/FAQ.md#how-to-implement-a-frameless-html-window) on how implement a  borderless window with enutronium
