### ISSUE TITLE
Can we  develop apps with transparency?

### ISSUE THREAD

**Issue by NOHJ-1** [NeutroniumCore/Neutronium#110]
Setting the `AllowTransparency=True, WindowStyle=None` on the `Window` causes the `HTMLViewControl` to be blank, yet still functioning. Like hovering when around, the cursor reacts to the controls on the HTML like buttons, and the click function works also.

Yet when `AllowTransparency=True, WindowStyle=None , Background="Transparent"` is set on the Window, nothing works anymore. Overriding the `UpdateChromiumBrowserSettings(CfxBrowserSettings browserSettings)` or `UpdateChromiumSettings(CfxSettings settings)` then setting the Background color to a transparent color does not work.

Is transparency possible? Like floating buttons on the desktop

**Comment by NOHJ-1** [comment]
After I posted this I made a lot of research about this and this seems to be an issue from a long time ago and is still on-going.

**Comment by NOHJ-1** [comment]
Hey I just found out that Awesomium can do this, that it can be transparent:

[Transparent Content in Webbrowser](https://stackoverflow.com/questions/17453064/transparent-content-in-webbrowser)

> Awesomium and Awesomium.NET is an HTML UI Engine that supports just that.

> Check the WPF WebControl. You can set WebControl.IsTransparent to true, and load some content with say body { background-color: transparent; } (you can even specify a custom CSS to be applied to all loaded pages, using WebSession).

And that you have [Neutronium.WebBrowserEngine.Awesomium](https://www.nuget.org/packages/Neutronium.WebBrowserEngine.Awesomium/). So then I immediately tried something which resulted in this one which does not work
```
protected override void OnStartUp(IHTMLEngineFactory factory)
        {
            base.OnStartUp(factory);
            factory.RegisterHTMLEngine(new Neutronium.WebBrowserEngine.Awesomium.AwesomiumWPFWebWindowFactory());

#if DEBUG
            SetUpForDeveloppment();
#else
            SetUpViewModel.InitForProduction();
#endif
            factory.RegisterJavaScriptFrameworkAsDefault(new VueSessionInjectorV2 { RunTimeOnly = true });
        }
```
because it caused this error:
```
System.TypeLoadException: 'Method 'get_Environment' in type 'Neutronium.WebBrowserEngine.Awesomium.AwesomiumWPFWebWindowFactory' from assembly 'Neutronium.WebBrowserEngine.Awesomium, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
```
which I'm not really sure how to do this since I found no document about changing browser engines.

In the [README.MD](https://github.com/NeutroniumCore/Neutronium), you mentioned

> Different from other libraries Awesomium is not open source. Last update was embedding Chrome 19 so it is pretty out of date. One neutronium distribution offer Awesomium as WebBrowser.

and since there's 'Neutronium.WebBrowserEngine.ChromiumFx' which is to 'Neutronium.ChromiumFx.Vue'.

**Comment by NOHJ-1** [comment]
Hey I just found out that Awesomium can do this, that it can be transparent:

[Transparent Content in Webbrowser](https://stackoverflow.com/questions/17453064/transparent-content-in-webbrowser)

> Awesomium and Awesomium.NET is an HTML UI Engine that supports just that.

> Check the WPF WebControl. You can set WebControl.IsTransparent to true, and load some content with say body { background-color: transparent; } (you can even specify a custom CSS to be applied to all loaded pages, using WebSession).

And that you have [Neutronium.WebBrowserEngine.Awesomium](https://www.nuget.org/packages/Neutronium.WebBrowserEngine.Awesomium/). So then I immediately tried something which resulted in this one which does not work
```
protected override void OnStartUp(IHTMLEngineFactory factory)
        {
            base.OnStartUp(factory);
            factory.RegisterHTMLEngine(new Neutronium.WebBrowserEngine.Awesomium.AwesomiumWPFWebWindowFactory());

#if DEBUG
            SetUpForDeveloppment();
#else
            SetUpViewModel.InitForProduction();
#endif
            factory.RegisterJavaScriptFrameworkAsDefault(new VueSessionInjectorV2 { RunTimeOnly = true });
        }
```
because it caused this error:
```
System.TypeLoadException: 'Method 'get_Environment' in type 'Neutronium.WebBrowserEngine.Awesomium.AwesomiumWPFWebWindowFactory' from assembly 'Neutronium.WebBrowserEngine.Awesomium, Version=0.6.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'
```
which I'm not really sure how to do this since I found no document about changing browser engines.

In the [README.MD](https://github.com/NeutroniumCore/Neutronium), you mentioned

> Different from other libraries Awesomium is not open source. Last update was embedding Chrome 19 so it is pretty out of date. One neutronium distribution offer Awesomium as WebBrowser.

and since there's 'Neutronium.WebBrowserEngine.ChromiumFx' which is to 'Neutronium.ChromiumFx.Vue'. There's no 'Neutronium.WebBrowserEngine.Awesomium' to 'Neutronium.Awesomium.Vue'. I'm not entirely sure what this means..

..Ok, so is this still possible?

**Comment by NOHJ-1** [comment]
..Awesomium no longer exists, since its now [Ultralight](https://github.com/ultralight-ux/ultralight), welp

**Comment by David-Desmaisons** [comment]
@NOHJ-1 ChromiumFx component is in fact an WindowsForm component embeded in Wpf using a WindowsFormsHost.
WindowsFormsHost have known limitation regarding transparency.

**Comment by NOHJ-1** [comment]
yes. but about the Awesomium part.. I installed your 'Unofficial.Awesomium.Complete' and it had the WebControl that I needed because

> Check the WPF WebControl. You can set WebControl.IsTransparent to true, and load some content with say body { background-color: transparent; } (you can even specify a custom CSS to be applied to all loaded pages, using WebSession).

..can you please read my post just previous to your post

**Comment by David-Desmaisons** [comment]
Awesomium is not a solution chromium 19 won't work with vue or other modern javascript solution.

**Comment by NOHJ-1** [comment]
*sigh ok.. Chromium 19 has no `ExecuteJavascriptAsync` function or anything that you can work on?

**Comment by NOHJ-1** [comment]
wait, then why's there a [Neutronium.WebBrowser.Awesomium](https://www.nuget.org/packages/Neutronium.WebBrowserEngine.Awesomium/) ?

**Comment by David-Desmaisons** [comment]
The main problem with Awesomium is not the bindings with Neutronium but the API linked to a very old version of Chromium (current version is something like 71- awesomium is 19). So many modern javascript API are not implemented and as such modern framework won't work.

**Comment by David-Desmaisons** [comment]
`wait, then why's there a Neutronium.WebBrowser.Awesomium ?

It is working with knockout. Still I do not maintain any nuget for the reason below.

**Comment by NOHJ-1** [comment]
ok I see. I really looked forward to developing transparent applications with Neutronium (and also that other guy who thumbed up my post).

Awesomium seems to be [Ultralight ](https://github.com/ultralight-ux/ultralight). Maybe you should have a look into it.

**Comment by David-Desmaisons** [comment]
Thanks for the tips about ultralight I will invetigate
