### ISSUE TITLE
Not able to find WebEngine exception

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#113]
Hi @David-Desmaisons 

trying to display and window with Neutronium for release notes, the first windows display correctly the html elements. After closing this window the main window  should start.

I get this exception, supose when closing the first window neutronium is being disposed. #111 tried to play with the https://neutroniumcore.github.io/Neutronium/articles/installing.html#for-an-existing-wpf-project but wihtout success.

my app is started like this:
        protected override void UpdateLineCommandArg(CfxOnBeforeCommandLineProcessingEventArgs beforeLineCommand)
        {
            beforeLineCommand.CommandLine.AppendSwitch("disable-web-security");
            beforeLineCommand.CommandLine.AppendSwitch("disable-gpu");
        }

        protected override IJavascriptFrameworkManager GetJavascriptUIFrameworkManager()
        {
            return new VueSessionInjector();
        }

        protected override void OnStartUp(IHTMLEngineFactory factory)
        {
            factory.RegisterJavaScriptFrameworkAsDefault(new VueSessionInjectorV2());
            base.OnStartUp(factory);
        }

        private void AppStartup(object sender, StartupEventArgs e)
        {
this.ShutdownMode = ShutdownMode.OnExplicitShutdown;
            var credWindow = new ReleaseNotesView(model);
            credWindow.ShowDialog();
            credWindow.Close();

            var mainWindow = new MainWindow(farmiCasePath, srcDir, tiaMap);
            mainWindow.Show();
            mainWindow.Activate();

      }

xaml:
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*" />
            <RowDefinition Height="30" />
        </Grid.RowDefinitions>
        <Neutronium:HTMLViewControl Grid.Row="0" x:Name="ReleaseNotesViewControl" IsDebug="True" RelativeSource="releasenotes.html"  />
        <StackPanel Orientation="Horizontal" Grid.Row="1">
            <CheckBox x:Name="DisplayNotesInNext" 
                                Content="untick for restart and skip release notes" IsChecked="{Binding DisplayOnRestart}" />
        </StackPanel>
    </Grid>

Not sure how i can handle this one, thanks.

**Comment by David-Desmaisons** [comment]
I can not see
```
engine.RegisterHTMLEngine(new ChromiumFXWPFWebWindowFactory());
```
in your code sample.

It seems that you are callling Dispose on HTMLEngineFactory when closing the first window, that should be done only when application is closing.

**Comment by jmecosta** [comment]
it has been working wihtout the RegisterHTMLEngine fine when eveyrthing is contained in a single mainwindow! but anyway.

added now:

        protected override void OnStartUp(IHTMLEngineFactory factory)
        {
            factory.RegisterJavaScriptFrameworkAsDefault(new VueSessionInjectorV2());
            factory.RegisterHTMLEngine(new ChromiumFXWPFWebWindowFactory());
            base.OnStartUp(factory);
        }
and disable the dispose:
    public partial class ReleaseNotesView
    {
        public ReleaseNotesView(ReleaseNotesViewModel model)
        {
            GC.Collect();
            this.DataContext = model;
            InitializeComponent();
            this.Unloaded += ReleaseNotesUnloaded;
        }

        public ReleaseNotesView()
        {
            GC.Collect();
            InitializeComponent();
            this.Unloaded += ReleaseNotesUnloaded;
        }

        private void ReleaseNotesUnloaded(object sender, RoutedEventArgs e)
        {
        }
    }

Same result tough
![image](https://user-images.githubusercontent.com/1041352/56111267-03659980-5f60-11e9-9f4f-ff6cbbf04c8d.png)

dont see any unload logging 
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\TestImpactRunnerApi.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\NuGet.Common.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration.Install\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.Install.dll'. Cannot find or open the PDB file.
Neutronium - Browser Log: Message: Neutronium: ViewModel injected, source: , line number: 11443, page: file:///E:/prod/tools/BuildTools/buildallextension/BuildDrop/TafApp/releasenotes.html
Exception thrown: 'System.IO.EndOfStreamException' in mscorlib.dll
The thread 0x3120 has exited with code 0 (0x0).
The thread 0x5210 has exited with code 0 (0x0).
The thread 0x48e4 has exited with code 0 (0x0).
The thread 0x23f8 has exited with code 0 (0x0).
The thread 0x4bfc has exited with code 0 (0x0).
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\CredentialManagement.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\TeamcityRestApi.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\FSharp.Core.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\RestSharp.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\MsbuildController.dll'. Symbols loaded.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\FarmiCaseHelpers.dll'. Symbols loaded.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\LibGit2Sharp.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\DotNetImpactHelpers.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\CppImpactHelpers.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\FarmiAdapterUtils.dll'. Symbols loaded.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\BullseyeCoverageToTiaProvider.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\GitSourceControlProvider.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\Newtonsoft.Json.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'E:\prod\tools\BuildTools\buildallextension\BuildDrop\TafApp\FSharp.Data.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Cannot find or open the PDB file.
'TafApp.exe' (CLR v4.0.30319: TafApp.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_64\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll'. Cannot find or open the PDB file.
Exception thrown: 'LibGit2Sharp.RepositoryNotFoundException' in LibGit2Sharp.dll
Exception thrown: 'LibGit2Sharp.RepositoryNotFoundException' in LibGit2Sharp.dll
Exception thrown: 'Neutronium.Core.Exceptions.NeutroniumException' in Neutronium.WPF.dll
Not able to find WebEngine 

thanks

**Comment by David-Desmaisons** [comment]
1) Are you using neutronium ChromiumFxWebBrowserApp?
If so you do not need to register the Cfx engine

2) The two ways that the HTMLEngine can be found at the first time and not after are:
-you explicitly asks for an unregistered engine in the second window using the HTMLEngine attribute: highly improbable

-you are disposing the HTMLEngineFactory between when opening the second window => highly probable

As closing the application will dispose the engine, you should check if the App is being closed when closing the window.

**Comment by jmecosta** [comment]
1. correct. that was the case
2. I only have one place where i do something with engine in the apps.cs. After that i just start and close windows!

i cant find anyway where im disposing it. ive done a skimmed example. with this one, for some reason the engine is not even displaying the html but i does get the dispose exception comming from not sure where from!
[example.zip](https://github.com/NeutroniumCore/Neutronium/files/3085424/example.zip)

**Comment by David-Desmaisons** [comment]
Nothing to do with Neutronium. Your release note calls   System.Windows.Application.Current.Shutdown();
So after that Neutronium won'twor.e Nothing strange.romyna
