### ISSUE TITLE
nullreference exception on instantiating neutronium

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#115]
Hi @David-Desmaisons 

Neutronium\Neutronium.Core\Binding\Listeners\ListenerUpdater.cs
        private void OnCommandCanExecuteChanged(object sender, EventArgs e)
        {
            var updater = _JsUpdaterFactory.GetUpdaterForExecutionChanged(sender);
            ScheduleChanges(updater);
        }

throw exception because for some magic reason sender is null. i cant figure out whats wrong with my code. however adding a check on sender is null will make the application work as expected. Nothing stop working if the check is there! Would it be possible if you could add that conditino there?

**Comment by David-Desmaisons** [comment]
In fact, this is command implementation that send an event with null sender.
So you should check your code base to correct this problem.

That said Neutronium should be resilient to interface implementation error, so I will implement the null check.

**Comment by jmecosta** [comment]
thanks im not exactly sure, why thise has surface now. Ive been using those RelayCommands for years wihout issues. I did update Neutronium to last version, but cant be sure if that triggered it.  I have another one! but this one is a bit more tricky not sure if this is because of the scenarion im implementing

Basically replace UserControl with another on without closing main window.
If i set this.DataContext = new model() then i get exception 

        private void ChromiumFxControl_Loaded(object sender, RoutedEventArgs e)
        {
            this.Loaded -= ChromiumFxControl_Loaded;
            _Window = Window.GetWindow(this); > returns null
            _WindowHandle = new WindowInteropHelper(_Window).Handle;
            _Window.Closed += Window_Closed;
            _Window.LocationChanged += _Window_LocationChanged;
            _Window.StateChanged += Window_StateChanged;
            UpdateDpiMatrix();
        }

Im not really sure what that means however, if i dont set the datacontext than everything works fine. If i also check for null and return
            _Window = Window.GetWindow(this);
            if (_Window == null)
            {
                return;
            }

Everything loads and works properly. Can you also implement this check?

**Comment by David-Desmaisons** [comment]
=> This is a differenet issue/question than the previous one so open an new issue, I will comment on the new one.

**Comment by jmecosta** [comment]
yep, sorry about that
