### ISSUE TITLE
Window.GetWindow returns null 

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#116]
Replace UserControl with another on without closing main window.
If i set this.DataContext = new model() then i get exception

    private void ChromiumFxControl_Loaded(object sender, RoutedEventArgs e)
    {
        this.Loaded -= ChromiumFxControl_Loaded;
        _Window = Window.GetWindow(this); > returns null
        _WindowHandle = new WindowInteropHelper(_Window).Handle;
        _Window.Closed += Window_Closed;
        _Window.LocationChanged += _Window_LocationChanged;
        _Window.StateChanged += Window_StateChanged;
        UpdateDpiMatrix();
    }
Im not really sure what that means however, if i dont set the datacontext than everything works fine. If i also check for null and return
_Window = Window.GetWindow(this);
if (_Window == null)
{
return;
}

Everything loads and works properly. Can you also implement this check?

**Comment by David-Desmaisons** [comment]
If this is hapenning that means that the component is loaded has it is not yet inserted in a window.
This is not something supported and simply ignoring this case may result in further bugs when window is resized or location changes as necessary events won't be listened. So this really an edge case that I am not sure this is a good idea to support.
The only thing I can think of rigth now would be change the corresponding code to raise a more explicit exception when this is hapenning.

Could you explain better your scenario? Why are you "replacing" UseControl?
Why not use the same and update the ViewModel?
Could check what is the callstack resulting in the loading of the usercontrol? Then could change your creation sequence to first add the usercontrol to the window.

**Comment by jmecosta** [comment]
ok, i found my issue. I set the model before setting the view. So possible a better execption message would show the mistake. thanks
