### ISSUE TITLE
UWP not possible

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#118]
@David-Desmaisons this is probably not possible right? Some context, new msix allows win32 apps to be put in store. Deployment works however running fails because cef cannit be loaded

**Comment by David-Desmaisons** [comment]
Currently only WPF is supported

**Comment by jmecosta** [comment]
I mean that with new msix you can bring wpf apps to be installed in store,
not sure if you are aware that. Not asking about having a port to uwp, but
just wondering if would it be possible to get those wpf installed into
store. I think its a deployment only thing. As far i read cef will not run
there, however since edge is building on top of chromiun wonder if this
will now be possible.

Distrubuting neutronium apps via store would be really great

**Comment by David-Desmaisons** [comment]
I will investigate later on, as far of Today, best way to package Neutronium application is to use click-once.

**Comment by jmecosta** [comment]
Alright thanks for checking, just a side note. Msix will allow wpf
applications to use windows 10 api. So it brings a all new user experience
to these applications
