### ISSUE TITLE
Question - Any way to serve view for any browser using neutronium as data backend?

### ISSUE THREAD

**Issue by joaquinabenza** [NeutroniumCore/Neutronium#121]
We are developing a netronium application but we would like to use it for any client web browser, using neutronium as backend for the node serving dist view.

**Comment by David-Desmaisons** [comment]
I am not sure if I get your point, Neutronium is designed for creating desktop application and waht you need seems to be be a classic ASP.MVC application. Sounds like you do not need Neutronium.
Could you explain better I may have lost some details.

**Comment by newsash** [comment]
@David-Desmaisons  I have a related question. There is a large desktop application with dozens of independent WPF GUI parts. I need to develop remote GUI (accessible over LAN) for this application somethere in future. I think this will be a Vue SPA, the plan is to replace WPF GUI parts with Vue components one by one. Can Neutronium somehow simplify this transition, or better to use ASP.NET MVC from the beginning?

P.S. I'm happy to see the ability to easily create HTML+CSS+JS GUI for .NET desktop applications. Thank you for this.

**Comment by genyx** [comment]
i am developing on an application with neutronium for over a year now. if you are not an absolut expert in vue.js or even if, you will face weird things with a chromium application like this.

if you are just at the beginning of your project, i recommend having a look at Blazor that integrates with Electron. I have not used it yet, but it is praised to be the next generation of web development (c# instead of js !!).

**Comment by newsash** [comment]
@genyx Thank you. I considered Blazor as another JS add-on (and I preferred Typescript), but now I have noticed that it's running on WebAssembly without transpilation to JS. I'll look into it.

**Comment by David-Desmaisons** [comment]
@newsash : I understand that long term, you will need a SPA + ASP.NET MVC, correct?

The main advantage of using Neutronium now is that you won't need to change your backend implementation as Neutronium is 100% compatible with WPF MVVM.
Then you can migrate the application to ASP.NET MVC. This way you will be able to re-use the components done in the first migration. 

Few words about blazor/Electron:
you will need to re-write both front-end and back-en at the same. If you need to have some sophisticated UI you will need to use the javascript integration, which is none trivial.
The decision point should be on your skill in javascript vs C# and how complex your UI is.

That said, I am considering an adaptor for blazor in Neutronium.

**Comment by newsash** [comment]
@David-Desmaisons I will need to make desktop application GUI accessible over LAN in Google Chrome (simultaneously with local GUI). If ASP.NET MVC will be best solution for this, than I'll need ASP.NET MVC. Thank you for the answer, there is sufficiently information for me to look into options and make a decision.
