### ISSUE TITLE
How to use vuetify v2.x?

### ISSUE THREAD

**Issue by HADB** [NeutroniumCore/Neutronium#124]
As [Vuetify 2.0 upgrade guide](https://github.com/vuetifyjs/vuetify/releases/tag/v2.0.0#user-content-upgrade-guide) saying, `Vuetify must now be instantiated and passed to the initial Vue instance.`

I added `option.vuetify = new Vuetify()` in `buildVueOption` of `entry.js`, but it didn't work but it worked in debug mode when I added `vuetify: new Vuetify()` in `vueRootInstanceOption` of `main.js`.

I can't figure out how to fix this, what's your suggestion?

Thanks!

**Comment by David-Desmaisons** [comment]
You should use the install file to add more option for the vue constructor.
This file exposes a `vueInstanceOption` function that returns all the options that need to be added.
Check for Example:

https://github.com/NeutroniumCore/Neutronium.SPA.Demo/blob/master/Neutronium.SPA.Demo/View/src/install.js
https://github.com/David-Desmaisons/DriveExplorer/blob/master/DriverExplorer.UI/View/src/install.js

**Comment by jmecosta** [comment]
@David-Desmaisons any hints on how to fix this? 

```js
const vueRootInstanceOption = Object.assign({}, vueInstanceOption() || {}, {
  render: h =>
    h(App, {
      props: {
        viewModel: vm.ViewModel,
        __window__: vm.Window
      }
    }),
    vuetify: new Vuetify(opts),
  data: vm
});
```
=> this works fine with npm run serve
If i run the c# app i get the vuetify is not started. 

Neutronium - Browser Log: Message: Error: Vuetify is not properly initialized, see https://vuetifyjs.com/getting-started/quick-start#bootstrapping-the-vuetify-object, source: , line number: 6, page: pack://application:,,,/View/dist/index.html

If i added to entry.js

```js
const opts = {
    theme: {
        dark: true,
    },
};
function buildVueOption(vm) {
    var option = vueInstanceOption(vm);
    option.vuetify = new Vuetify(opts);
  option.render = function(h) {
    const prop = {
      props: {
        viewModel: this.$data.ViewModel,
        __window__: this.$data.Window
      }
    };
    return h(App, prop);
  };
  return option;
}
```

then no error, however i get nice black page! 
![image](https://user-images.githubusercontent.com/1041352/105642800-b92f7d00-5e94-11eb-97ad-5b584b4d6b66.png)

Any hints how to properly fix this. Would really be great to migrate the vuetify 2.x

**Comment by David-Desmaisons** [comment]
You add to use the `install.js`  script to add option to the vue instance for both serve and build scenario.
More specifically modify the implementation of the `vueInstanceOption` function to return vuetify options
```js
function vueInstanceOption(vm) {
//...
  const vuetify = new Vuetify(myOptions);
  return {
      // other stuff...,
      vuetify,
    };
}
```


Check the https://github.com/David-Desmaisons/Ornette/ repo who is a working example using vuetify.2

In particular: https://github.com/David-Desmaisons/Ornette/blob/master/Ornette/View/src/install.js

**Comment by jmecosta** [comment]
ok, excelent. Thanks for the updated sample. Must have checked before!
