### ISSUE TITLE
ChromiumFXRenderProcess.exe crash problem

### ISSUE THREAD

**Issue by HADB** [NeutroniumCore/Neutronium#125]
Recently, we found our app will show blank screen after running in 4K screens for some time.

We are using large images for 4K screens which may cause more cpu and memory using.

Memory using of ChromiumFXRenderProcess.exe will growing up to about 400M and then the process will go missing which causes blank screen.

And sometimes, ChromiumFXRenderProcess.exe will not be killed after the main application exited.

It seems ChromiumFXRenderProcess.exe is uncontrollable.

I found ChromiumFX has some new release after 3.3440.x, will these updates be useful?

What do you suggest to locate the problem?

Thanks!

**Comment by David-Desmaisons** [comment]
1) You may use Chromium inspector memory tabs to try get more information of the problem
2) Are you using 64 bits builds this may help with memory problem.
3) The updates may be useful as Chromium keeps improving its memory performance, I will provide in the short/mid-term.

It will be also nice if you couls list your application here: https://github.com/NeutroniumCore/Neutronium/issues/12

**Comment by HADB** [comment]
Thanks for replying.

We reduced the size of these large images yesterday and never see blank screens again.

I will go digging this problem after our project launched.

**Comment by HADB** [comment]
Update:
Using 64 bits builds solve this problem. 

Problem I found while using 64 bits builds:
#127
