### ISSUE TITLE
There is no functional - compilable "knockout" example

### ISSUE THREAD

**Issue by etheaven** [NeutroniumCore/Neutronium#126]
I'm interested in the "knockout" example, which if I understand correctly is a version where no Vue is used. Is there any working one? I couldn't find any.

**Comment by David-Desmaisons** [comment]
You can install it from the VS templates: 
https://marketplace.visualstudio.com/items?itemName=DavidDes.NeutroniumApplicationTemplates

It is also available by nuget: 
https://www.nuget.org/packages/Neutronium.ChromiumFx.Knockout/

You have some working examples on this repo too:
https://github.com/NeutroniumCore/Neutronium/tree/master/Examples/Example.ChromiumFX.Ko.UI

**Comment by etheaven** [comment]
The knockout one from the VS template does not compile, you must delete "dist" folder, if you do so, you only see black window with no changes at all, so I guess dist is where html template is taken from, however it does not work in the VS template.

as for the repo, it does not compile if cloned. VS 2017 - couldn't find any getting started in the readme, would you provide me steps to compiling the Example.ChromiumFX.Ko.UI ?

**Comment by David-Desmaisons** [comment]
It seems to me that you do not check the option of downloading nugets on build.
Could you try to restore nugets before building the project from the VS template?
Same thing apply to this repo. In fact, this repo has CI which use only nuget restore and standard msbuild to build the project.

**Comment by etheaven** [comment]
I seriously need help. Whatever I try, it doesn't build. I only need to test out the Ko.UI project but I can't build it at all. All I did was clone it and start the solution, right click the project and build. What do I need to do to build it?

**Comment by David-Desmaisons** [comment]
```
dotnet restore ./Neutronium.MVVMComponents/Neutronium.MVVMComponents.csproj --verbosity m
dotnet restore ./Tests/Neutronium.MVVMComponents.Test/Neutronium.MVVMComponents.Test.csproj --verbosity m
nuget restore
```

+ build

What is the erro you get? at wwhich step?
