### ISSUE TITLE
64 bits of Neutronium.WebBrowserEngine.ChromiumFx.dll is not updated in v1.5.2

### ISSUE THREAD

**Issue by HADB** [NeutroniumCore/Neutronium#127]
There's no property called `AllowGpu` in 64 bits of `Neutronium.WebBrowserEngine.ChromiumFx.dll` in v1.5.2 release.

It seems 64 bits of this file is 1.5.0 in 1.5.2 release.

**Comment by David-Desmaisons** [comment]
Publish version 1.6.0 that correct it
