### ISSUE TITLE
Open Inspector programatically

### ISSUE THREAD

**Issue by genyx** [NeutroniumCore/Neutronium#129]
Is it possible to open the Chromium Inspector from C#? I like to disable the debug-rightclick-menu-thing, but still be able in some situations in Release environment to access the chromium dev tools.

**Comment by David-Desmaisons** [comment]
Sorry for the long delay:
IWPFWebWindow  has a OnDebugToolsRequest method that will open the debug window.
It is accessible via the WPFWebWindow property of HTMLWindow and  HTMLViewControl.
