### ISSUE TITLE
Template for Visual Studio 2017

### ISSUE THREAD

**Issue by intoxopox** [NeutroniumCore/Neutronium#13]
Current template is for VS 2015. Will a VS 2017 version be provided?

**Comment by David-Desmaisons** [comment]
Hello @intoxopox, It is on my TODO list, I will provide them after releasing Neutronium next version.

**Comment by EddyCwdry** [comment]
Is there any documentation on how to set up a solution from scratch or a way to set it up without the extension? I couldn't see anywhere in the repo where the template solution is kept.

**Comment by David-Desmaisons** [comment]
Hi @EddyCwdry, I just finished to release Neutronium 0.5.0 which contains many significative improvements. 
My focus now is on creating template/example and updating the documentation.
I will provide the documentation you ask for shortly.

**Comment by David-Desmaisons** [comment]
@EddyCwdry , Here is the documentation on how to sey-up project from scratch: https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/SetUp.md#from-scratch

**Comment by intoxopox** [comment]
Nice! Any estimate on the 2017 template?

**Comment by David-Desmaisons** [comment]
@intoxopox , I would say next week

**Comment by intoxopox** [comment]
Hi. Any updates on this?

**Comment by David-Desmaisons** [comment]
@intoxopox , I just updated Neutronium templates. Version 2.8 contains last version of Neutronium (0.6.0) and is compatible with VS2015 and VS2017.
