### ISSUE TITLE
Drag&Drop not working

### ISSUE THREAD

**Issue by Tywele** [NeutroniumCore/Neutronium#130]
I'm not quite sure what the cause of this is but I'm unable to use SortableJS for example to enable drag and drop of lists or tables. It just doesn't do anything. I tried reproducing it in jsfiddle. It's working there but the same code is not working in Neutronium: https://jsfiddle.net/7dsLcgv3/

Is anyone able to confirm this?

**Comment by David-Desmaisons** [comment]
Do you have a repo with the code for reproduction? Did you check the console and verify all scripts get loaded?
There is no reason this should not work.
