### ISSUE TITLE
Is Neutronium still maintened?

### ISSUE THREAD

**Issue by TartanLeGrand** [NeutroniumCore/Neutronium#133]
I'm looking for a framework to make better interfaces than what WPF can offer. But I feel like the project's dead?

**Comment by David-Desmaisons** [comment]
Hello @TartanLeGrand , Neutronium is still maintened.
I am providing bug fix on the current version if needed.
I still need to find sometime to update to last Cfx version and provide VS2019 templates but it is planned.
