### ISSUE TITLE
Missing Example for ICommand CanExecute Implementation

### ISSUE THREAD

**Issue by simonbuehler** [NeutroniumCore/Neutronium#135]
hi,

the Documentation does not show any usage of the `CanExecute` Method.
How can i eg.  bind a vue textbutton to a ICommand implementation that enables e.g. the button when the current time second is odd?

Where can the `RelaySimpleCommand` `CanExecute`  Method be implemented?

**Comment by David-Desmaisons** [comment]
`RelaySimpleCommand ` does not have any `CanExecute ` method. Indeed `ISimpleCommand` inteface is designed for command than can always be executed.

If you need to invalidae command, every implementation of `ICommand ` will work with Neutonium  but you may use `RelayToogleCommand`  that Neutronium provides: changing `ShouldExecute` property will triger CanExecuteChanged events.

Alternativelly you may implement a RelayCommand by yourself check [here](https://stackoverflow.com/a/22286816/1544783).
