### ISSUE TITLE
incorrect dll packaged in Neutronium.WebBrowserEngine.ChromiumFx x64 1.5.2

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#138]
hi @David-Desmaisons 

seems Neutronium.WebBrowserEngine.ChromiumFx to be having some configuration issues. Ive check IlSpy and 
AnyCpu
![image](https://user-images.githubusercontent.com/1041352/77845971-7ee54880-71bb-11ea-8ff8-8f5de0083b54.png)

x64 is still on 1.5.0
![image](https://user-images.githubusercontent.com/1041352/77845993-945a7280-71bb-11ea-97db-3c758212c01e.png)

can you check this please! meanwhile i use local build nuget packages and 1.5.2 x64 produces 1.5.2 assemblies, it seems that you package the 1.5.0 assembly in the 1.5.2?
![image](https://user-images.githubusercontent.com/1041352/77846052-f31fec00-71bb-11ea-9b3a-af631f97dda9.png)

**Comment by jmecosta** [comment]
the missing method exception was related with the upgrade of 
```
    <PackageReference Include="Unofficial.Chromiumfx" Version="3.3440.1808" />
```
to
```
<PackageReference Include="Unofficial.Chromiumfx" Version="77.1.18" />
```
```
ChromiumWebBrowser.Initialize(true);
```
might need adjustment

**Comment by David-Desmaisons** [comment]
Current version of Neutronium is not compatible with version 77.1.18 of ChromiumFx.
It will be released a new version of Neutronium very soon.
