### ISSUE TITLE
serialize observable collection

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#139]
hi @David-Desmaisons 

since normal observable collection is serializble across domains, can the Range collection behave in similar manner?

I get exception when running my macros in dedicated domain and passing range collection to the runner

thanks

**Comment by David-Desmaisons** [comment]
I am not sure which implementation of Range collection you are refering to, but Neutronium is not exposing one. 
There is one implementation only for test in a test assembly and no need to make it serializable.

You should write your own implementation of range collection and provide the serialize behavior.

**Comment by jmecosta** [comment]
right, my confusion. thought https://github.com/NeutroniumCore/Neutronium/blob/master/Tests/UniversalTests/HTMLBindingTests/Helper/ObservableRangeCollection.cs was part you the official api! 

sorry about this
