### ISSUE TITLE
Cross Platform?

### ISSUE THREAD

**Issue by zezba9000** [NeutroniumCore/Neutronium#14]
Is this project cross platform (Win, Lin and Mac)? Or windows only?

**Comment by David-Desmaisons** [comment]
Hello @zezba9000 , while Neutronium.Core is platform agnostic, Neutronium.WPF is windows only.
It main be part of Neutronium roamap to provide a Linux version but not in the short-term

**Comment by zezba9000** [comment]
Are there any tips on what API feature I would use get the CEF / Neutronium.Core hardware accelerated backbuffer for use with D3D / GL etc? Or many a better option exists such as registering with a window handle?

Before I could use the product would need to do some tests on Linux and macOS. Tnx for any tips

**Comment by David-Desmaisons** [comment]
@zezba9000 , You can abble disable chromium switch using CEF API, 
[See documentation here](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Accessing_Chromium_API.md) I guess that this what you need 

Regarding Linux and macOS support, I might not have been clear, but this not currently in the roadmap.
