### ISSUE TITLE
how to mock design data comming from a promise

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#140]
hi @David-Desmaisons 

im using a RelayResultCommand and a promise on view side. i need to get some mocked data to work on design time. however if i save the vm.cjson there will be no errors when calling the RelayResultCommand there are no exceptions so i can catch it and provide my own mocked version of the data. 

is there a elegant way of hanlding this? what im doing is to manually modify a flag the vm.csjon to tell its design time so he shouldnt use the promise

thanks in advance

**Comment by David-Desmaisons** [comment]
> is there a elegant way of hanlding this? what im doing is to manually modify a flag the vm.csjon to tell its design time so he shouldnt use the promise

Could you explain better?

I will try to find an improved way to deal with command in design mode.

**Comment by jmecosta** [comment]
On Fri, 10 Apr 2020, 16:09 David Desmaisons, <notifications@github.com>
wrote:

> is there a elegant way of hanlding this? what im doing is to manually
> modify a flag the vm.csjon to tell its design time so he shouldnt use the
> promise
>
> Could you explain better?
>
Just we dont get any data out from command in design mode. So need to do it
with workarounds.

> I will try to find an improved way to deal with command in design mode.
>
Alright thanks, for now i will use some properties to simulate the return
data of the command.

**Comment by David-Desmaisons** [comment]
Check version 1.4.0 of neutronium-vm-loader

https://github.com/NeutroniumCore/neutronium-vm-loader

**Comment by jmecosta** [comment]
Cool thanks
