### ISSUE TITLE
System.InvalidCastException => object => string

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#141]
@David-Desmaisons  i think this is a bug. If u have a dropbox with a set of objects, clearing them to empty makes this kind of exception.  i think in this case Neutronium should set null instead of string.Empty.

```
TafApp.exe Information: 0 : Neutronium - Info: Unable to set C# from javascript object: property: SelectedPerfCheck of TafModel.Helpers.PerfTestCase, javascript value . Exception System.InvalidCastException: Unable to cast object of type 'System.String' to type 'TafModel.Helpers.PerfTestCase'.
   at SetSelectedPerfCheck(Object , Object )
   at Neutronium.Core.Binding.BidirectionalMapper.<>c__DisplayClass43_1.<OnJavaScriptObjectChanges>b__0() was thrown.
The thread 0x4820 has exited with code 0 (0x0).
```

**Comment by David-Desmaisons** [comment]
It seems that you are trying to set from javascript a string to a property of type TafModel.Helpers.PerfTestCase.
This is not supported. Set it to null instead.

**Comment by jmecosta** [comment]
how?
![image](https://user-images.githubusercontent.com/1041352/78995500-2151e400-7b4b-11ea-9dcb-d9f1955ec424.png)

im clearing a combo box from UI, i dont have any access to set it to null... or am i missing something?

this combobox is connectect to a property 

```
        <v-combobox
          :disabled="viewModel.SelectedCase == null || viewModel.LoadingData"
          :loading="viewModel.LoadingData"
          v-model="viewModel.SelectedTargetBranch"
          item-text="Name"
          :items="viewModel.TargetBranches"
          label="Branch"
        ></v-combobox>
```
