### ISSUE TITLE
bind to images / video

### ISSUE THREAD

**Issue by simonbuehler** [NeutroniumCore/Neutronium#142]
hi,

what is the best practice to push a video  / images captured from a webcam and processed in c# code to the gui?
in WPF the binding to a bitmap property is fast enough for 30+fps, whats the way to do this here?

any hint would be great!

**Comment by simonbuehler** [comment]
got it working, not performance optimized but working

```
  public static string GetByteArrayFromImage(BitmapSource writeableBitmap)
        {
            JpegBitmapEncoder encoder = new JpegBitmapEncoder();
            encoder.Frames.Add(BitmapFrame.Create(writeableBitmap));
            MemoryStream stream = new MemoryStream();
            encoder.Save(stream);
            Byte[] bytes = stream.ToArray();
            return Convert.ToBase64String(bytes);
        }
```
and 

```
<img v-bind:src="'data:image/jpeg;base64,'+imageBytes" />
```

**Comment by David-Desmaisons** [comment]
Thanks for posting this and sorry for the late answer.
I end up doing something very similar to bind to an image from a memory stream.
Performance wise how it is performing?

**Comment by simonbuehler** [comment]
Quite fast, but heap is filling up :/


![grafik](https://user-images.githubusercontent.com/78061/83929768-df34cf80-a794-11ea-9502-665f0c066ca6.png)

and 

![grafik](https://user-images.githubusercontent.com/78061/83929872-363aa480-a795-11ea-923a-88e8b764b7ac.png)

**Comment by simonbuehler** [comment]
It seems the cache is filling up, how can a binding can be defined as 'no cache' or force cache to limit size or purge manually?

Guess that's a new issue here?

**Comment by simonbuehler** [comment]
Closing, memory issue in #146

**Comment by David-Desmaisons** [comment]
I just commeted on issue #146 . Is your code open source? I may use it to perform some benchmarks.

**Comment by simonbuehler** [comment]
a quick demo: https://github.com/simonbuehler/CamDemo

**Comment by David-Desmaisons** [comment]
Still curious about the performance of this code. Did you perform some measurement?

**Comment by simonbuehler** [comment]
Not yet, will have to look into your test cases to build a stress test. Thinking about one which generates many e.g. 100kb random strings and pushes them to a vue property and when received issues a 'received' call to c# and the next is pushed until the loop is done. Measuring the total time with the cleanup true/false should give meaningful results?

**Comment by David-Desmaisons** [comment]
The test you are proposing is interesting,
I had in mind something more integrated real performance of your scenario (that said, not sure how get the fps).
