### ISSUE TITLE
observable collection not properly update in web view

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#15]
@David-Desmaisons hi

have  weird problem with some observable collection:

Have this vue template bind to Packages
```xml
          <demo-grid  :data="Packages"
                    :columns="gridColumns"
                    :filter-key="searchQuery">
          </demo-grid>
```

the component for vue:
```javascript
Vue.component('demo-grid', {
    template: '#grid-template',
    props: {
        columns: Array,
        filterKey: String
    },
    data: function () {
        var sortOrders = {}
        this.columns.forEach(function (key) {
            sortOrders[key] = 1
        })
        return {
            sortKey: '',
            sortOrders: sortOrders
        }
    },
    computed: {
        filteredData: function () {
            var sortKey = this.sortKey
            var filterKey = this.filterKey && this.filterKey.toLowerCase()
            var order = this.sortOrders[sortKey] || 1
            var data = this.$parent.Packages
            if (filterKey) {
                data = data.filter(function (row) {
                    return Object.keys(row).some(function (key) {
                        return String(row[key]).toLowerCase().indexOf(filterKey) > -1
                    })
                })
            }
            if (sortKey) {
                data = data.slice().sort(function (a, b) {
                    a = a[sortKey]
                    b = b[sortKey]
                    return (a === b ? 0 : a > b ? 1 : -1) * order
                })
            }
            return data
        }
    },
```

When i do in c# side this.Packages.clear() then the web component clears all packages, however when i repopulate the list altought the c# side contains the correct values the web still shows the old values.

see debug data
![image](https://cloud.githubusercontent.com/assets/1041352/25795625/e2373650-33de-11e7-8c7a-74a904a8dee7.png)

after repopulate vue debugwindow
![image](https://cloud.githubusercontent.com/assets/1041352/25795648/f3eb6e52-33de-11e7-9819-8900569ddb61.png)

if i close the web component and restore it again then it brings new values.

if forcing adding new items they will be double but still with old values. is there something i should do to force refresh the values?

thanks

**Comment by David-Desmaisons** [comment]
Hello @jmecosta two questions:

1) It seems that you are re-using same object before and after update. Is it correct?
2) Is Version property implementing correctly the INotifyProperty pattern?

It seems to me that Version value is changed and that the event is not fired.

So correcting this should solve the problem. You don't even have to clear and add objects to display change

**Comment by jmecosta** [comment]
@David-Desmaisons indeed, thanks. i was trusting the observable collection would fire those events. But of course it only fires when collection changes. Not when the underlying object changes. implementing inotify pattern in the class solved the issue.

thanks alot for the help
