### ISSUE TITLE
An unhandled exception of type 'Chromium.CfxException' occurred in ChromiumFX.dll  Additional information: libcfx library not found.

### ISSUE THREAD

**Issue by Moradnejad** [NeutroniumCore/Neutronium#17]
I recently upgraded to the latest version of Microsoft Visual Studio 2015.
I first used the template to start. But it gives me the additional dll error.

Also I downloaded the whole project and tried some of examples. 
For example for ChromiumFX.Ko.UI: It builds all of the dlls (even libcfx), but still gives the following error.

> An unhandled exception of type 'Chromium.CfxException' occurred in ChromiumFX.dll
> Additional information: libcfx library not found.

Is there any configuration (like cpu config) or any other thing that i'm not doing? I simply downloaded and build and tried to run a project.

**Comment by David-Desmaisons** [comment]
Hello @Moradnejad, it seems that some nuget pacakages did not install correctly. The Unofficial.Chromiumfx brings C libs including libcfx . Please make sure that all nugets installed correctly and try to reinstall them.

**Comment by Moradnejad** [comment]
Thanks David. When I build the project, it restores and gets these libs. I will try again and will send you a picture of the contents. Thanks again

**Comment by David-Desmaisons** [comment]
Any new on this @Moradnejad ?
