### ISSUE TITLE
Usage with C++

### ISSUE THREAD

**Issue by sksar** [NeutroniumCore/Neutronium#18]
I am creating a C++ application where i would like to embed Neutronium (not .net application).
Any documentation or help to get started ?

**Comment by David-Desmaisons** [comment]
Hello @sksar , I am not sure I understand your scenario. Are you using C++ / CLI?

**Comment by sksar** [comment]
@David-Desmaisons,  Yes, i am using native C++ and i am trying to keep my code portable so i am not using .net

**Comment by sjoerd222888** [comment]
@David-Desmaisons please correct me if I am wrong.

As far as I know this is not easily possible. You would need to write a wrapper library with .Net and then use then call the C# library as described for example [here](https://code.msdn.microsoft.com/windowsdesktop/Consuming-C-Library-in-937458e5).
However you would required to implement all your view-models and related logic in C#.

And I am not aware of a plain C++ alternative of Neutronium which would be the most convenient approach I think.

**Comment by David-Desmaisons** [comment]
@sksar  I agree with  @sjoerd222888  there is no easy way to go with pure C++ as Neutronium as been designed  for .Net application. For C++, you should consider a lower level integration such as [CEF ](https://bitbucket.org/chromiumembedded/cef)
