### ISSUE TITLE
Package html assets in WPF resource

### ISSUE THREAD

**Issue by lhyqy5** [NeutroniumCore/Neutronium#20]
Is there any way to package html assets into WPF resource, then use [pack uris](https://docs.microsoft.com/en-us/dotnet/framework/wpf/app-development/pack-uris-in-wpf) to set HTMLViewControl's RelativeSource property. So we can hide the html files instead of leaving them in the filesystem.

**Comment by David-Desmaisons** [comment]
Hello @lhyqy5 pack uri can not be used out of the box and links referenced on the corresponding file should be availiable to http requests. That said I understand the need of "hiding" HTML files and CEF provide some features for such needs. I will take a look at what alternative solution I can provide.

**Comment by lhyqy5** [comment]
Hi @David-Desmaisons 

Maybe I found some way to do this, according to [this](https://bitbucket.org/chromiumembedded/cef/wiki/GeneralUsage#markdown-header-request-handling) and [this](https://bitbucket.org/chromiumfx/chromiumfx/issues/21/how-do-i-add-a-custom-schema) I make some code  here
 https://github.com/NeutroniumCore/Neutronium/compare/master...lhyqy5:pack-uri?expand=1
Could you review these code and it’s my pleasure to make a PR.

**Comment by David-Desmaisons** [comment]
Hello @lhyqy5 , it looks very promising you can open a PR with these changes provided you also add corresponding test and/or example. Thanks for contributingl
