### ISSUE TITLE
libcfx library not found

### ISSUE THREAD

**Issue by metherul** [NeutroniumCore/Neutronium#22]
Heya! I noticed that there was a closed issue which had this same problem, but that no solution was posted. 

Using the current version of the Visual Studio Neutronium VueJS template breaks on runtime with an Chromium.CfxException error because of a missing libcfx.dll library. I've reinstalled the Nuget packages as per recommended in #17 , but it didn't solve the crash. Just a note that I am running on VS 2017, so that _might_ be the issue, although I doubt it. 

Any ideas as to why this may be happening? 

Here's the debug log (well, at least part of it). 
```
An unhandled exception of type 'Chromium.CfxException' occurred in ChromiumFX.dll
libcfx library not found.
```

**Comment by David-Desmaisons** [comment]
Please delete the packages folder of your project and restore all the nuget packages.

**Comment by metherul** [comment]
Restoring NuGet packages didn't solve the issue, sadly.

**Comment by David-Desmaisons** [comment]
Did you remove the packages folder ?
If so could you check the content of the Unofficial.Cef.for.Chromiumfx.3.2924.0 folder inside packages folder?

**Comment by metherul** [comment]
Aye, I removed packages and then did a complete Nuget restore. 

And here's the tree from Unofficial.Cef.for.Chromiumfx.3.2924.0 -

```
C:.
│   test.txt
│   Unofficial.Cef.for.Chromiumfx.3.2924.0.nupkg
│   
└───build
    │   Unofficial.Cef.for.Chromiumfx.targets
    │   
    └───cef
        └───Release
                libcef.dll
                

```

**Comment by David-Desmaisons** [comment]
Hello @metherul , I tried it from scratch and it works normally. If you did not have done it yet, you could  try create a new project and desintall-reinstall  the visual studio template.

**Comment by metherul** [comment]
I was hoping that it would work, but still, nothing. Same issue as before.

**Comment by metherul** [comment]
@David-Desmaisons I finally have the time to start doing some testing. Could it be an issue with Windows 10? Doubt it, but it may be a possibility.

**Comment by David-Desmaisons** [comment]
@metherul , I have done all my testing with Windows 10. Did you try to clean your local nuget cache if any?

**Comment by metherul** [comment]
@David-Desmaisons Nope, no effect at all. An annoying issue, I'm sure. Where is the libcfx.dll library located in your build? Mine's located in the same directory as the executable.

**Comment by David-Desmaisons** [comment]
Should be under `cef\Release` the nuget take care of this changing post build hook.
Are tou trying to make a x64 or anyCpu build?

**Comment by metherul** [comment]
@David-Desmaisons Super sorry about the slow reply, I totally forgot to respond!
Yep, it's located in that directory and x64, x86 and AnyCpu builds all fail.

**Comment by krconv** [comment]
I was having the same issue; adding a new configuration for x86 and switching to it from AnyCPU solved it for me.

**Comment by David-Desmaisons** [comment]
@metherul Any updates on this?

**Comment by metherul** [comment]
@David-Desmaisons Nah, went for pure WPF with Material Design in XAML instead -- never had any success with getting Neutronium (or any of your sample projects) to build. 

It's annoying, because this same issue has happened on two completely different machines. I'm sure it's hard to debug on your end, so bear with me.
