### ISSUE TITLE
Neutronium and localization

### ISSUE THREAD

**Issue by o2genum** [NeutroniumCore/Neutronium#23]
I have a question [here](https://stackoverflow.com/questions/46393329/how-to-localize-neutronium-based-ui-using-resx-files). I'd be grateful if you could share some ideas of how to do the .resx-based localization easier.

**Comment by David-Desmaisons** [comment]
Hello @o2genum , I post an answer on stack-overflow, we can let this thread open to discuss improvement linked to localization:
1) Dynamic object support
2) better support for dictionary conversion
3) vue localization integration

**Comment by o2genum** [comment]
Thank you.
So, dictionaries are supported to some extent? Somehow I had missed it and didn't try it.

I think dynamic object support would be good but non-essential, it's quite a hack for such a purpose, and now I think these static localization strings don't really belong to ViewModel.

So I like the third option, Vue-side localization and moving most strings to the Vue side. Could you suggest a good plugin for this, and does it require support from Neutronium?

My only requirement is instant language switching, without app restart: ViewModel should probably provide a LanguageCode property, and upon its update all ViewModel properties would have to be reloaded, and all localization strings in the UI would be reloaded as well.

**Comment by David-Desmaisons** [comment]
1) Dictionary are IEnumerable<KeyValuePair<TKey,TValue>> as such they will be converted by neutronium as array.
2) Thanks for the feedback, I also see dynamic support as none essential
3) [vue-i18n](https://github.com/kazupon/vue-i18n) should be the way to go, that said it won't work out of the box with neutronium. Extra plumbing will be required.

**Comment by o2genum** [comment]
Ok. I guess it's possible to integrate `vue-i18n` without modifying Neutronium internals, and I can manage it myself? Or you're aware of some issues that will require deeper integration, like modifying C# Neutronium code?

**Comment by David-Desmaisons** [comment]
If it is possible to set dynamically messages in vue-i18n then you can use a life-cyce hook to set its value from component data and it should do the trick. If not things will be more complicated.

**Comment by David-Desmaisons** [comment]
Hello @o2genum both dictionary and dynamic will be suported in next version.

**Comment by David-Desmaisons** [comment]
@o2genum I just updated my stackoverflow answer.

**Comment by o2genum** [comment]
Thanks, this is awesome. I think I'll try explore `vue-i18n` and stick to it for now. Let me know if you're about to release the new version. Resource wrapped in dynamic/dictionary means less refactoring for me, while `vue-i18n` may be more architecturally right thing to use, though.

**Comment by David-Desmaisons** [comment]
@o2genum I intend to release next version within this month, this will be a hughe update. 
Regarding `vue-i18n`  I am still unclear on how to integrate it whithin the tradicional MVVM patern thougth it will make Neutronium development closer to wed development. I guess this needs more study and analysis.

**Comment by o2genum** [comment]
Now trying to use `vue-i18n` with single file components, and I can't get it to work.
On `vue-i18n`:

[Installation](https://kazupon.github.io/vue-i18n/en/installation.html)
[Getting Started](https://kazupon.github.io/vue-i18n/en/started.html)
[Single FIle Components](https://kazupon.github.io/vue-i18n/en/sfc.html#basic-usage)

I asked [a SO question](https://stackoverflow.com/questions/46869516/vue-i18n-single-file-component-initialization-with-neutronium-library) with details on this. If you have an idea how to initialize Vue for Neutronium the way `vue-i18n` wants it or you have some experience with `vue-i18n`, please, check my question.

**Comment by David-Desmaisons** [comment]
@o2genum , do you have a git repository with the corresponding code?

**Comment by o2genum** [comment]
https://github.com/o2genum/NeutroniumI18nExample

**Comment by o2genum** [comment]
And this seems to be an official example for localization with `<i18n>` single file component blocks:
https://github.com/kazupon/vue-i18n/tree/dev/examples/sfc

I'm going to try it now, I wonder if works at all.

**Comment by o2genum** [comment]
Ok, this official example does work:
https://github.com/kazupon/vue-i18n/tree/dev/examples/sfc

**Comment by o2genum** [comment]
Ok, I got `vue-i18n` working, but only in browser, without Neutronium (`npm run dev`).
Here's the code: https://github.com/o2genum/NeutroniumI18nExample

With Neutronium, `$t('hello')` gets translated once, and does not update upon changing the locale. So Neutronium seems to get in the way somewhere, I wonder how. Also, I don't know how to pass `:view-model=$data` now.

Do you have an idea where `vue-i18n` and Neutronium may conflict?

[`vue-i18n` ](https://github.com/kazupon/vue-i18n/tree/dev/src) and [`vue-i18n-loader`](https://github.com/kazupon/vue-i18n-loader) code seems pretty simple.

`vue-i18n` has some watching and subscriptions in [`vue-i18n/src/mixin.js`](https://github.com/kazupon/vue-i18n/blob/dev/src/mixin.js), for example, I guess this may be the conflicting part.

**Comment by o2genum** [comment]
Okay, I got it working. It only works in this order, `vue-i18n` initialization has to happen after `VueGlue register` event:

![image](https://user-images.githubusercontent.com/658230/32026825-8cf04182-b9ee-11e7-9920-4895449fc103.png)

Now I use `setTimeout()` to delay `vue-i18n` initialization, but I need something better. I need to hook to `VueGlue register` event or something like that.

And the last problem is that I don't know how to pass `:view-model="$data"` now.

Here's my code: https://github.com/o2genum/NeutroniumI18nExample

**Comment by David-Desmaisons** [comment]
@o2genum , In version 1.0.0, it will be possible to pass Vue instance option parameter so that you can initialize `vue-i18n` or any other library needing passing option to Vue root instance.

To do so you need to export a vueInstanceOption function returning Vue instance option.

Example:

```javascript
import VueI18n from 'vue-i18n'
import {messages} from './messages'

function install(vue) {
    //Call vue use here if needed
    vue.use(VueI18n);
}

function vueInstanceOption() {
    const i18n = new VueI18n({
        locale: 'ru', // set locale
        messages, // set locale messages
    });

    //Return vue global option here, such as vue-router, vue-i18n, mix-ins, .... 
    return {i18n}
}

export {
    install,
    vueInstanceOption
} 
```
See [documention](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Build_large_project_with_Vue.js_and_Webpack.md).

NB: I will release version 1.0.0 very shortly.

**Comment by David-Desmaisons** [comment]
@o2genum  I just released version 1.0.0

**Comment by David-Desmaisons** [comment]
@o2genum , See the new answer on [stackeoverflow](https://stackoverflow.com/questions/46393329/how-to-localize-neutronium-based-ui-using-resx-files/47006355#47006355) and the complete[ example here](https://github.com/NeutroniumCore/Neutronium/tree/master/Examples/Example.Option.CFx.Vue).

**Comment by o2genum** [comment]
Thanks! Somehow did it with 0.6.0, all vue-i18n init code and strings are in App.vue for now.
I'm planning on checking out 1.0.0 soon, it should make my code cleaner.
