### ISSUE TITLE
Is neutronium supporting AnyCpu and x64 ?

### ISSUE THREAD

**Issue by Bjaris** [NeutroniumCore/Neutronium#25]
Hi ,
I am not sure it is the good place to ask such question.

We are currently evaluating WebControl to integrate in  Prism based applications. 
These applications are mostly x32 and x64  and so libraries that are also AnyCpu can be a big plus as it is a way to avoid to have  x86 and x64 variant of the libs.
I tried to execute some samples in x64 and it seems it is not working. I noticed also that even if the sample are AnyCpu  option prefer 32 bit is checked resulting in a 32 bit application.
So the question is 
Does Neutronium support x64 application ? Do you provide any CPU libs using on x86 and x64 applicatiion ?

Thx in advance for your answer

Additionnal information 
Example.Awesomium.CefGlue.Ko.SimpleU
Modify the project to build truly build it as AnyCPU (uncheck prefer 32 bit)
Start in debug on a WIndows X64 
You have this exception  =>System.BadImageFormatException on Neutronium.WPF assembly surely because it is not x64 or anyCPU

**Comment by David-Desmaisons** [comment]
Hello Bjaris, this is a good place for such question!

Neutronium can support x64 builds with ChromiumFx. 
As by today I have not generated ChromiumFx nugget for 64 builds which should use C++ 64 builds, but once this is done this is just a matter of referencing them. 
I prototyped it not long ago and it works fine.
So this is just a matter of generating this libs and finding out a way to have platform specific nuggets.

For any cpu, I guess this should be possible, I have to check.

**Comment by Bjaris** [comment]
Thanks you for your swift answer. If I understand well I have "just" to build ChromiumFx for x64 and replace references in the project  by the newly generated one ?

**Comment by David-Desmaisons** [comment]
And using x64 distribution of CEF.
Correct.

**Comment by fizxmike** [comment]
Any progress on this. I need the x64 support since my project depends on other x64 only libraries... Looks like I have to pull down NeutoriumCore and re-build with x64, linking in ChomiumFX (built for x64) and CEF (which fortunately has x64 nuget package)?

**Comment by jmecosta** [comment]
@David-Desmaisons if you want i can push a pull request with this?

**Comment by fizxmike** [comment]
@jmecosta if you put it up on your fork first, I can test it out. Much thanks! I've tried doing this myself, but I'm new to VisualStudio. It seems frustrating how you can't add a reference that is not a COM object to have it copy to your build directory automatically... I'm facing issue with CEF finding all it's .pak files correctly, and since it's all .cc code, I don't get to debug where it's looking.

**Comment by David-Desmaisons** [comment]
@fizxmike I will release a new Neutronium version this week-end. I will take chance to investigate the release of x64. I recently found an issue with maximal nuget package size, I will see if you can work around.

@jmecosta , thanks every PR is welcome. I am not sure what you have in mind thougth as the 64 nugget is more about building-packaging than code changes.

**Comment by fizxmike** [comment]
Ok, I got it to work. It was a pain, and maybe I did it the hard way (please let me know if there is easier way to do this) but it seems to work just fine. For me I had to build ChomiumFX (and friends) for x64, and then build NeutroniumCore (and friends) for x64, then manually copy in the right version of CEF from here: http://opensource.spotify.com/cefbuilds/index.html (there is a file in ChromiumFX repo that tells you which will work) and copy Resource and Release folders to [build]\cef
the final trick was to move the icudtl.dat file from [build]\cef\Resources\ to [build]\cef\Release\

**Comment by David-Desmaisons** [comment]
@fizxmike for local build basically this is it. The hard way, the only way!
Nuget generation is even more painfull I am taking a look on how to do it and have both 32 and 64 bits packages.

**Comment by jmecosta** [comment]
I supose then it's done, will be waiting for the release. Thanks

**Comment by David-Desmaisons** [comment]
Well @jmecosta , I wish it was simplw as that!
Still working on it.

**Comment by David-Desmaisons** [comment]
@Bjaris , @fizxmike , @jmecosta  I have made good progress on this one, I have created a local  ChromiumFx nuget package that can be used to create x86 or x64 application. Working on AnyCPU right now. Estimation that I should be abble to release a new Neutronium version and nugets supporting x64 builds

**Comment by jmecosta** [comment]
Just curious, why any cpu? Tought you usually target x86 or x64. Since
native stuff you can't target anycpu

**Comment by David-Desmaisons** [comment]
Almost there:
![image](https://user-images.githubusercontent.com/524617/34024247-45fc8614-e130-11e7-950b-e1f0933db55d.png)

**Comment by David-Desmaisons** [comment]
@jmecosta, Neutronium assemblies and exe, as well as .Net assemblies can by compiled using AnyCPU, even if at the end of the day a x86 or x64 native dll will be loaded.

**Comment by jmecosta** [comment]
Yes I am aware of that, however if a anycpu assembly uses a native dll it
no longer by definition is a anycpu assembly and many times it causes bugs
at runtime. I had one that a anycpu assembly with prefer 32 bit (the
default) was trying to use handle.exe and it cannot use it because it was
prefer 32 bit. So it's a bit misleading and some times confusing. We tend
to use anycpu only when there we know there is no dependencies to native
side. Also the project configurations are typically cleaner, so you have
x64 and win32 only, instead of having a mixed of stuff that most of the
times its really hard to get right

**Comment by David-Desmaisons** [comment]
@jmecosta got your point. Well ChromiumFx has the capability to be build in anycpu and resolve at runtime if its the win32 or x64 version of CEF, so it should work.
First tests that I performed are OK, but upon further tests if it shows to be error prone I can limit the build option to x86 and x64.

**Comment by David-Desmaisons** [comment]
Released in version 1.2.0
