### ISSUE TITLE
Example using ReactiveUI

### ISSUE THREAD

**Issue by desarrollo03TR** [NeutroniumCore/Neutronium#29]
I'm using ReactiveUI for my projects and I need an example using that MVVM framework.

Thanks!

**Comment by David-Desmaisons** [comment]
Hello @desarrollo03TR , I can provide such an example. That said there will be nothing ReactiveUI specific in the sense that this framework is proving implementation of ICommand and view model implementing INotifyPropertyChanged. Since Neutronium react propertly to this interface, nothing ReactiveUI  needs to be done

**Comment by desarrollo03TR** [comment]
Then, can I reuse my ViewModels from, for example, a WPF project? cool. Can I subscribe to my observables from my view using Knockout?

**Comment by David-Desmaisons** [comment]
@desarrollo03TR you are correct in both cases:
1) it is totally possible to reuse ViewModels from an existing MVVM WPF projects. 
2) Properties are converted into knoock-out observable that you can subscribe on js side.

That said I will strongly recomend you give a try to the integration with vue as it has better tooling including full vue debugger and web-pack tools.

**Comment by desarrollo03TR** [comment]
I'm testing an app and ReactiveUI works updating the UI, but the UI is not updating the VM. Maybe I'm not using the right html code?

**Comment by David-Desmaisons** [comment]
Well, it is a possibility. Check the visual studio trace, Neutronium logs binding problems there. If the problem persist you can share the html here or create a repo on github withe the corresponding code.

**Comment by desarrollo03TR** [comment]
Everything is working fine now, the code (if you want to try):

The ViewModel:

`using ReactiveUI;
using System.Reactive;

namespace Neutronium_knockout_Application1.ViewModel
{
    public class Person
    {
        public string FirstName { get; }
        public string LastName { get; }
         
        public Person(string name, string skillType)
        {
            FirstName = name;
            LastName = skillType;
        }
    }

    public class PersonViewModel : ReactiveObject
    {
        private string lastName;
        private string firstName;
        private ReactiveList<Person> _persons;
        private ObservableAsPropertyHelper<ReactiveList<Person>> persons;


        public PersonViewModel()
        {
            _Persons = new ReactiveList<Person>();

            this.WhenAnyValue(vm => vm._Persons)
                .ToProperty(this, vm => vm.Persons, out persons);

            var canAddPerson = this.WhenAnyValue(vm => vm.FirstName, vm => vm.LastName, (firstName, lastName) => !string.IsNullOrEmpty(firstName) && !string.IsNullOrEmpty(lastName));
            RemovePerson = ReactiveCommand.Create<Person>(person => Remove(person));
            AddPerson = ReactiveCommand.Create<PersonViewModel>(_ => Add(FirstName, LastName), canAddPerson);
        }


        public string LastName
        {
            get { return lastName; }
            set { this.RaiseAndSetIfChanged(ref lastName, value); }
        }

        public string FirstName
        {
            get { return firstName; }
            set { this.RaiseAndSetIfChanged(ref firstName, value); }
        }

        private ReactiveList<Person> _Persons
        {
            get => _persons;
            set => this.RaiseAndSetIfChanged(ref _persons, value);
        }

        public ReactiveList<Person> Persons => persons.Value;

        public ReactiveCommand<PersonViewModel, Unit> AddPerson { get; private set; }
        public ReactiveCommand<Person, Unit> RemovePerson { get; private set; }


        private void Remove(Person person)
        {
            this._Persons.Remove(person);
        }

        private void Add(string firstName, string lastName)
        {
            this._Persons.Add(new Person(firstName, lastName));
        }
    }
}`

The View:

`<!doctype html>
<html>
<head>
    <title>KnockOut.js Example</title>
</head>
<body>
    Testing ReactiveUI
    <input type="text" data-bind="value: FirstName, valueUpdate:'afterkeydown'" placeholder="First name">
    <input type="text" data-bind="value: LastName, valueUpdate:'afterkeydown'" placeholder="Last name">
    <button data-bind="command: AddPerson">Add</button>

    <ul data-bind="foreach: Persons()">
        <li><span data-bind="text:FirstName"></span>:<span data-bind="text:LastName"></span><button data-bind="command: $root.RemovePerson">Remove</button></li>
    </ul>
</body>
</html>`

**Comment by David-Desmaisons** [comment]
Hello @desarrollo03TR , I am glad you were able to make this work. Thanks also for sharing the working example.
