### ISSUE TITLE
Complex View with shared components example

### ISSUE THREAD

**Issue by tulpn** [NeutroniumCore/Neutronium#3]
Hi David, 

Is it possible to provide an example for a sample project with two different views (similar to the navigation example), that share a single component and interact with the same data. 

For instance, Page 1 & Page 2 share the same Menu which is included in the top of each page. 

When clicked on a menu item, the page is loaded and the menu is updated to highlight the clicked item. On page 1 could be a list of Persons and on Page 2 you could add a Person. 

The examples so far show how to do the single parts, but not how to combine these things without copy & pasting for instance the menu for each page. But maybe I am missing the point ? In the real world it is unmanagable to have two header menus and keep them the same across multiple files. Specifically when there is much more complex data, than just "menu items".

**Comment by David-Desmaisons** [comment]
Hello @tulpn, 
There are different ways: you can achieve what you described:

1) You can use two different HTMLViewControls, or one HTMLViewControl and one HTMLWindow, the first responsible to display the menu, and the second to display the page view model, Basically the datacontext of the first usercontrol remains static, whereas the second is changing with the view.

2) Use an SPA approach where you will use only one  HTMLViewControl amd HTMLView and multiple vue components that will dispaly the current page. You main want to use webpack or browserify to create and reuse .vue files and build the corresponding files before using them in Neutronium.


I am already working on providing more realistic examples for Neutronium. Expect to see these examples in the near future.

**Comment by David-Desmaisons** [comment]
@tulpn For structuring an application with neutronium take a look at: [NeutoniumDemo](https://github.com/David-Desmaisons/NeutoniumDemo) it is a demo application base on solution 1 including navigation and IoC.
In order to reuse component consider using webpack with neutronium as described here: [Build large project with Vue.js and Webpack](https://github.com/David-Desmaisons/Neutronium/wiki/Build-large-project-with-Vue.js-and-Webpack)

**Comment by David-Desmaisons** [comment]
See reference project : [Neutronium.SPA.Demo](https://github.com/NeutroniumCore/Neutronium.SPA.Demo) for solution 2 implementation
