### ISSUE TITLE
Vue Router

### ISSUE THREAD

**Issue by genyx** [NeutroniumCore/Neutronium#31]
Can i use the `vue-router` for simply switching multiple pages/views?

**Comment by David-Desmaisons** [comment]
Hello @genyx, it is currently not possible to use vue-router with Neutronium.

Indeed Neutronium is creating the root vue instance using corresponding viewmodel and vue-router implies that you create a vue instance using the router:
```
const router = new VueRouter({
  routes
})
const app = new Vue({
  router
}).$mount('#app')
```
This presents two chalenges: how to pass extra-data to the vue instance and how to allow alternative vue instanciation in Neutronium.
I will study further vue-router to see if I see a way to integrate.

You can also take a look at discussion of issue #26 that raise similar problems but offer alternative to vue-router.

**Comment by David-Desmaisons** [comment]
@genyx , in version 1.0.0, it will be possible to pass Vue instance option parameter. This means that it will be possible to use `vue-router`

To do so you need to export a vueInstanceOption function returning Vue instance option in the neutronium-vue install.js file

Example:

```javascript
import VueRouter from 'vue-router'

function install(vue) {
    //Call vue use here if needed
    vue.use(VueRouter);
}

function vueInstanceOption() {
    const router= new VueRouter ({
    });
    //Return vue global option here, such as vue-router, vue-i18n, mix-ins, .... 
    return {router}
}

export {
    install,
    vueInstanceOption
} 
```
See [documention](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Build_large_project_with_Vue.js_and_Webpack.md)

NB: I will release version 1.0.0 very shortly.

**Comment by genyx** [comment]
Thanks man. But i probably will go with the dynamic components thing.

The 1.0.0 release will be on nuget? Asking because i currently use this repo self compiled. Nuget would be much easier.

**Comment by David-Desmaisons** [comment]
@genyx , It should be available very shortly, probably at the end of the week.

**Comment by David-Desmaisons** [comment]
@genyx , I just released version 1.0.0

**Comment by David-Desmaisons** [comment]
@genyx you can take a look at [Neutronium.SPA.Demo](https://github.com/NeutroniumCore/Neutronium.SPA.Demo).
It is a template project featuring routing, dependcy injection and integration with vue-router.
Soon I will add internalization, and in breve I will add diocumentation.

**Comment by David-Desmaisons** [comment]
@genyx , I am closing this one: Neutronium.SPA.Demo](https://github.com/NeutroniumCore/Neutronium.SPA.Demo) is a reference example of integration with vue-router. I am providing the complete documenattion.
