### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by renanpc** [NeutroniumCore/Neutronium#32]
I'm opening here to continue the discussion started in mvvmawesomium issue.

I have already tried using ChromiumFX and CefGlue, and got the same error in both, I tried ChromiumFX first, now I'm trying CefGlue.
The exception is throwed inside 
InjectInHtmlSession of the class BidirectionalMapper.

Do you have any idea of what could be ?

Thanks !

**Comment by renanpc** [comment]
This is the stack trace

`  em Neutronium.Core.Binding.BidirectionalMapper.<InjectInHtmlSession>d__33.MoveNext() na C:\Source\Aplus.Coin2.0\Neutronium.Core\Binding\BidirectionalMapper.cs:linha 146
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   em Neutronium.Core.Binding.BidirectionalMapper.<>c__DisplayClass25_0.<<UpdateJavascriptObjects>b__0>d.MoveNext() na C:\Source\Aplus.Coin2.0\Neutronium.Core\Binding\BidirectionalMapper.cs:linha 82
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em Neutronium.Core.Binding.BidirectionalMapper.<UpdateJavascriptObjects>d__25.MoveNext() na C:\Source\Aplus.Coin2.0\Neutronium.Core\Binding\BidirectionalMapper.cs:linha 70
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   em Neutronium.Core.HtmlBinding.BindingBuilder.<Neutronium-Core-IBindingBuilder-CreateBinding>d__4.MoveNext() na C:\Source\Aplus.Coin2.0\Neutronium.Core\HtmlBinding.cs:linha 86`

**Comment by David-Desmaisons** [comment]
Please:
1) add application trace
2) specify the version of Neutronium used

**Comment by renanpc** [comment]
Neutronium version 1.0.0

Which trace do you want, InteliTrace file (.itrace) ?

**Comment by David-Desmaisons** [comment]
Visual studio debug trace

**Comment by renanpc** [comment]
Here it is !
[DebugTrace.txt](https://github.com/NeutroniumCore/Neutronium/files/1438572/DebugTrace.txt)

**Comment by David-Desmaisons** [comment]
Please check main differences beetween Neutronium and MVVM.For.Awesomium:

1) Check application initiazation using example as refrences.
2) You do not have to include lnockout.js script in the main index. It is done automatically.
3) Introduction of an intermediate ViewModel element as direct child of the root.See [here].(https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Migrate_from_0_6_to_version_1_0.md#viewmodel-binding)
4) Use Visual studio template as a reference.

**Comment by renanpc** [comment]
Adapting the HTML it run fine, but only with CefGlue, chromiumFx load everything but don't show nothing in the window opened, the buttons InspectVM, Inspect and About appears. The window Inspect VM doesn't open, the Inspect show the HTML correctly, but the rendering of the inspect window appear to have some glitches img attatched.

![glitchs](https://user-images.githubusercontent.com/6960326/32408245-e5554e82-c17b-11e7-9814-c23ba1d957ee.png)

The webbrowser engine chromiumfx supports navigation like cefglue?

Another question, there is some option to enable gpu rendering ?

Thanks.

**Comment by David-Desmaisons** [comment]
Check the nuget packages. Install Neutronium.Knockout.Chromium 1.0.0 and check that every Neutronium package is version 1.0.0.

Second question: [here](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Accessing_Chromium_API.md)

**Comment by renanpc** [comment]
I checked everything, I have installed all the packages through nuget, every Neutronium package is on version 1.0.0.

**Comment by renanpc** [comment]
The same glitch occur on ChromiumFX project example.

**Comment by David-Desmaisons** [comment]
Did you try using the Visual Studio templates?

**Comment by renanpc** [comment]
I discovered why the chromiumFX was not working, it was because of some transparency options which were enable in my window.xaml.

If the window is configured with a transparent background or the grid which contains the chromium, I think it render but don't show.

Another problem is when you try to use the visibility of the wpf:HTMLWindows as false, and after start the application you set to true, the program stop working. In my case, I was setting the visibility of the HTMLWindow to true only when the IsHtmlLoaded was true.

To solve the rendering glitches I had to deactivate some gpu options and enable other options of chromiumFX.

options bellow:
`beforeLineCommand.CommandLine.AppendSwitch("disable-web-security");
            beforeLineCommand.CommandLine.AppendSwitch("off-screen-rendering-enabled");
            beforeLineCommand.CommandLine.AppendSwitchWithValue("off-screen-frame-rate", "25");
            beforeLineCommand.CommandLine.AppendSwitch("disable-gpu");
            beforeLineCommand.CommandLine.AppendSwitch("disable-gpu-compositing");
            //beforeLineCommand.CommandLine.AppendSwitch("disable-gpu-vsync");
            beforeLineCommand.CommandLine.AppendSwitch("enable-begin-frame-scheduling");
            beforeLineCommand.CommandLine.AppendSwitch("enable-media-stream");`

The only problem I'm having now is about the update of some fields and collections, when another thread update ViewModel values an exception is thrown, but I think if I use the dispatcher this problem will be solved.

About the performance, The chromiumFx made the animations very fluid the screen navigation and animations got very smooth too, I'm very confident that will be possible to migrate everything from awesomium to chromiumFx using neutronium.

Thanks for your help.

**Comment by David-Desmaisons** [comment]
Glad you make it worked.
Chromium option will depend on the hardware configuration.

Since version 1.0.0, Neutronium is not dispatching updates to the UI thread but expect any changes on viewmodel to happened on the UI thread.
Mainly for performance reason and for conformance with WPF.

Using WPF will fix this.
