### ISSUE TITLE
Will Neutronium Eventually Supports React?

### ISSUE THREAD

**Issue by stevefan1999-personal** [NeutroniumCore/Neutronium#36]
Maybe we could run some "diet React" like Preact and Inferno? Does it really need to be MVVM framework on the HTML5+JS side?

**Comment by David-Desmaisons** [comment]
Hi @stevefan1999 , in fact Neutronium needs something like a "reactive engine" (in the sense of reactive programming) where it can send the changes observed and that can be listened (via listener/subscriber pattern) for changes.
As such it would be possible to connect Neutronium with library such as RxJS, Cycle.js or marko.

React and similar ( Preact, Inferno, ...) are "only" view engine"s and all data and event management should be handled separatly uusally using redux or flux. By themselves these tools also lack reactivty, leaving to the programmer the responsability to manage data and changes.

It could be possible to "connected" to Neutronium to a react-like library using for RxJS but I guess it will be a very unnaturall solution.

**Comment by stevefan1999** [comment]
I guess we should try out MobX, it can be both a reactive engine and a state management library, killing two birds with one stone. 

However, the pattern for MobX should be strange for most devs of the Camp Flux-Redux...

**Comment by David-Desmaisons** [comment]
I was not aware of MobX but it exactly fit the needs of a reactive engine to be plugged between Neutronium and React.

Basically implementating a javascript framework binding with Neutronium consists in implementing the [`IJavascriptFrameworkManager`](https://github.com/NeutroniumCore/Neutronium/blob/5036656c34d0b1c200eff9c1aba59e51073476d9/Neutronium.Core/JavascriptFramework/IJavascriptFrameworkManager.cs) interface and as consequence [`IJavascriptViewModelManager `](https://github.com/NeutroniumCore/Neutronium/blob/da003c6292efc30b253cc9df7eb465659811b05a/Neutronium.Core/JavascriptFramework/IJavascriptViewModelManager.cs),  [`IJavascriptSessionInjector `](https://github.com/NeutroniumCore/Neutronium/blob/9b14713234281c1140afc417fdd2c17fc407b119/Neutronium.Core/JavascriptFramework/IJavascriptSessionInjector.cs) and [`IJavascriptViewModelUpdater `](https://github.com/NeutroniumCore/Neutronium/blob/6990a23b21a8d44ee531793d831e95cb2cc75137/Neutronium.Core/JavascriptFramework/IJavascriptViewModelUpdater.cs).

So these are only 4 interfaces without having to adjust the core engine, Best way to do it is to create a dedicated assembly just like for Vue.js and Knockout.js. Contibution are welcome!

**Comment by David-Desmaisons** [comment]
Hello @stevefan1999 , just to let you know I started an experimental integration with mobx than could open the open to integration with react/preact and inferno.

**Comment by stevefan1999** [comment]
Damn, I couldn't believe you did that🤣
I will try to squeeze some time for that, but I'm focusing on new school semester and C++ game engineering right now. I have some idea for https://github.com/NeutroniumCore/Neutronium/compare/mobx_integration#diff-2f492ccafe89d0cc0b5643b2fd6dfb75

**Comment by David-Desmaisons** [comment]
Well untill this discussion I was not aware of mobx. After study it looks like a perfect fit for a  "reactive engine" that I mentioned"and at the same time offering integration with React and alike.
Rigth now prototipe integration is going much faster than anticipated. 
Stay tuned...

**Comment by David-Desmaisons** [comment]
Got 100% of binding integrated test passing. now working on the tooling/cli.

**Comment by vector-man** [comment]
Would it be difficult to get this working with ReactiveUI too?

**Comment by David-Desmaisons** [comment]
@vector-man In fact Neutronium is already working with ReactUI as ReactUI provides binding to WPF and Neutronium is 100% compatible with WPF

**Comment by stevefan1999-personal** [comment]
cool, may worth a try
