### ISSUE TITLE
Pack URL bug

### ISSUE THREAD

**Issue by o2genum** [NeutroniumCore/Neutronium#37]
The new `pack:///` url feature seems to be buggy.

From time to time Chromium is unable to read random packed files (I run the same executable each time, without rebuilding, and sometimes it happens). For big files it happens more frequently. Add something like 30K-line javascript to reproduce it. Unexpected end of input, unexpected token, etc., each time on a random line.

![capture](https://user-images.githubusercontent.com/658230/32909011-6b446002-cb16-11e7-8563-2663cd2641b7.PNG)

If I click `build.js:1` to go to that line, dev tools close. The affected files are missing Sources tab. It I click Application tab, dev tools close.

Maybe the contributor @lhyqy5 knows what's wrong.

**Comment by David-Desmaisons** [comment]
Could you share the corresponding project/file?

**Comment by o2genum** [comment]
I'll make up a sample project to reproduce it.

**Comment by o2genum** [comment]
Must be related to the copying of data between the streams: [PackUriResourceHandler.cs](https://github.com/NeutroniumCore/Neutronium/blob/master/WebBrowserEngine/ChromiumFX/HTMEngine.ChromiumFX/WPF/PackUriResourceHandler.cs)

[Related ChromoumFX docs](https://chromiumfx.bitbucket.io/api/html/T_Chromium_CfxResourceHandler.htm).

**Comment by David-Desmaisons** [comment]
@o2genum , I just corrected it. It was one nasty issue due to the way of ChromiumFx manage memory (using weak references) that may lead to hard to reproduce bug.

**Comment by o2genum** [comment]
Ok. I suspected the copying of data in [PackUriResourceHandler.cs](https://github.com/NeutroniumCore/Neutronium/blob/master/WebBrowserEngine/ChromiumFX/HTMEngine.ChromiumFX/WPF/PackUriResourceHandler.cs) and it is coded a bit awkwardly, indeed. It only works because `ResponseLength` is set.

I corrected it according to the ChromiumFX docs (the code below), maybe you can include this fix, too. This is unrelated to the issue, though.

Will you make a release for this fix?

```
            ReadResponse += (s2, e2) =>
            {
                if (resInfo != null)
                {
                    var buffer = new byte[e2.BytesToRead];
                    var bytesRead = resInfo.Stream.Read(buffer, 0, e2.BytesToRead);
                    System.Runtime.InteropServices.Marshal.Copy(buffer, 0, e2.DataOut, bytesRead);
                    e2.BytesRead = bytesRead;

                    if (bytesRead != 0)
                    {
                        e2.SetReturnValue(true);
                    }
                    else
                    {
                        e2.SetReturnValue(false);
                    }
                }
            };

            ProcessRequest += (s3, e3) =>
            {
                e3.SetReturnValue(true);
                e3.Callback.Continue();
            };
```

**Comment by David-Desmaisons** [comment]
Are you refering to this alteration:
```
   if (bytesRead != 0)
   {
         e2.SetReturnValue(true);
   }
  else
   {
         e2.SetReturnValue(false);
   }
```
?

The new version should be available shortly.

Could you comunicate what kind of application you are creating with Neutronium?
Would you be ok to share some screenshots on Neutronium documentation to ilustre aplication made with Neutronium?

**Comment by o2genum** [comment]
This alteration, also unnecessary `Continue()` in `ReadResponce`, also wrong order (`Continue()`, then `SetReturnValue()`) in `ReadRequest` and `ProcessRequest`.

Ok, I'll share the app description and screenshots when I got it working (we're in process of switching to Neutronium-based UI).

**Comment by David-Desmaisons** [comment]
Ok Thanks.
I will take a look at the alteration, and commit them after review.

**Comment by David-Desmaisons** [comment]
I updated handler based on this two references:

https://bitbucket.org/chromiumfx/chromiumfx/src/25c83dc7ef6f204e85645725bf27fdfcd639e176/ChromiumWebBrowser/WebResource.cs?at=default&fileviewer=file-view-default

https://bitbucket.org/chromiumfx/chromiumfx/issues/21/how-do-i-add-a-custom-schema

I did not find any reference on `e2.SetReturnValue(false);`

**Comment by o2genum** [comment]
Ok. I only looked at what [the docs](https://chromiumfx.bitbucket.io/api/html/T_Chromium_CfxResourceHandler.htm) say.

`e.SetReturnValue(false)` is for signalling end of input, but when `e.ResponseLength` is set, this is not necessary (Chromium stops reading before the end of input is met). So I think it's ok as it is.

**Comment by David-Desmaisons** [comment]
Thanks for the link. I made another alteration to the original base on this doc.
