### ISSUE TITLE
support hidpi screens with neutronium

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#40]
hi @David-Desmaisons 

displaying Neutronium when custom scaling level is set to more than 100% for example in hi dpi screens causes widgets to render incorrectly. see screenshot 

![image](https://user-images.githubusercontent.com/1041352/32992352-4b3de100-cd52-11e7-8e64-df3d5909c77e.png)

maybe related: https://github.com/cefsharp/CefSharp/issues/1803

**Comment by David-Desmaisons** [comment]
Hi @jmecosta.
Thanks for the hint, I will add the corresponding `CfxRuntime.EnableHighDpiSupport()`
 in the next version

**Comment by David-Desmaisons** [comment]
Corrected by commit ae3bdc4106140a3c0fc59c4413fe91e281260f4c

**Comment by David-Desmaisons** [comment]
@jmecosta Could you confirm this fix worked?

**Comment by jmecosta** [comment]
@David-Desmaisons no, still same problem

  <package id="Neutronium.WebBrowserEngine.ChromiumFx" version="1.0.1" targetFramework="net45" />


[20171201_183322.zip](https://github.com/NeutroniumCore/Neutronium/files/1522234/20171201_183322.zip)

ive made a small video of the thing

**Comment by David-Desmaisons** [comment]
Using version 1.0.1 correct?

**Comment by jmecosta** [comment]
yep, forgot to escape the versioning
