### ISSUE TITLE
Does Neutronium support running in a class library and showing windows on demand?

### ISSUE THREAD

**Issue by frederikstonge** [NeutroniumCore/Neutronium#41]
I'm looking into your framework for an Office Add-in built with NetOffice. Microsoft has started working on their javascript api, which is far from complete now. Using your framework would give us an hybrid app so we could migrate more easily to their javascript add-in if it ever gets powerful enough.

**Comment by David-Desmaisons** [comment]
Hello @virulentt , I am not sure if I fully understand your question. At the end of the day, Neutronium offers WPF custom controls, so if in your sofware you can call WPF window API Show, you should be abble to address your scenario.

**Comment by virulentt** [comment]
The issue is that office add-ins are run from another thread, and all cef framework i've tried won't initialize. I think the workaround is to use remoting, which is implemented out of the box in ChromiumFX, but i don't know how your framework works exactly and if it supports that.
