### ISSUE TITLE
async find 

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#44]
hi @David-Desmaisons 

was looking to use vue.js multiselect with async find, wonder if this would be a use case with neutronium. so like this?

```
asyncFind (query) {
      this.isLoading = true
      ajaxFindCountry(query).then(response => {
        this.countries = response
        this.isLoading = false
      })
    },
```

you can for example, issue a command and then update the view from the cs side, but this is a bit more concise way

regards

**Comment by David-Desmaisons** [comment]
@jmecosta , you have a way to adress this kind of scenario using Neutronium: using `IResultCommand` instead of `ICommand`. I just added documentation [here](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Vue_Binding.md#advanced-iresultcommand-support).

In your case you substitute the call to the ajax by the following:

```javascript
import {toPromise} from 'neutronium-vue-resultcommand-topromise'

asyncFind (query) {
      this.isLoading = true
      toPromise(viewModel.CountryFinder, query).then(response => {
        this.countries = response
        this.isLoading = false
      })
    },
```

with:
```CSharp

public IResultCommand CountryFinder {get;}
```

**Comment by jmecosta** [comment]
Well that's nice. Thanks

**Comment by jmecosta** [comment]
@David-Desmaisons i was able to get the async working. like this

```
this.RunMacroAsync = RelayResultCommand.Create<string, Task<bool>>(this.OnRunMacroAsync);
```
it all works, apart from a small glitch. During the sending of the command all wpf ui is actually locked. but the html side is not.

So if the command is a long running command, users might be starting to jump to another tab, and they will not be able to.

thanks

**Comment by jmecosta** [comment]
actually also non async command lock the wpf part, and its a bit hard since im launching new process with output redirect and all the application just locks after i start using Application.Current.Dispatcher.Invoke when updating either the log in the html or wpf side

**Comment by David-Desmaisons** [comment]
> it all works, apart from a small glitch. During the sending of the command all wpf ui is actually locked. but the html side is not.
This is how promise works and how it is designed. If you need to limit the number of call, you can use a flag `isrunning` on on Js side to prvenet various call to run at the same time.

> async command lock the wpf part, 
Well this is also be design as command trigerred by WPF events. Of course you can use task to dispatch long working compoutation without locking the UI thread:

```
    private async ExececuteCommand()
    {
        await Task.Run(DoheavyComputation);
    }
```

**Comment by jmecosta** [comment]
thanks, i tried that and it still does not do what i want. but likely has more to do how i do the task synchronization than anything. if i use normal commands it works just fine. so i will stick to this for now. thanks
