### ISSUE TITLE
how to acess the vm from events in v1.0.0

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#45]
hi @David-Desmaisons 

i use this CodeMirror and i have 

```
                editorTestCase = CodeMirror(document.getElementById("codeTestCase"), {
                    mode: "text/x-csharp",
                    extraKeys: { "Ctrl-Space": "autocomplete" },
                    lineNumbers: true,
                    value: this.ViewModel.MacroCodeInEditor
                });

                editorTestCase.on("change", function (object, data) {
                    if (data.origin === "setValue") {
                        return;
                    }
                    try {
                        this.ViewModel.SelectedFTC.SelectedMacro.Content = data.text;
                        this.ViewModel.SaveNeeded = true;
                    } catch (e) {
                    }
                });
```

earlier with previous we were able to access it by using
this.vm.SelectedFTC.SelectedMacro.Content = data.text;
since vm was available in all context. so to update teh editor data in c# im a bit stuck

but now ViewModel is no longer available in that context

thanks

**Comment by David-Desmaisons** [comment]
Hello @jmecosta , It is difficult to answer you because i do not have the component hierarchy you are using.

Basically all you could do in 0.6.0, you will able to do in 1.0.0, only difference is that you have this extra viewModel props.

I would guess that maybe `this.ViewModel.vm.SelectedFTC.SelectedMacro.Content = data.text` will resolve. In any case, use the vue devtools embedded in neutronium debug to understand the current viewModel and find the property.

**Comment by jmecosta** [comment]
hi @David-Desmaisons 

when the event triggers ViewModel is not available

![image](https://user-images.githubusercontent.com/1041352/33243273-806e77f6-d2eb-11e7-9253-69577c4b5ea5.png)

earlier it was not available either. but there is this.vm i could access the data in the viewmodel

![image](https://user-images.githubusercontent.com/1041352/33243320-7da7ecd6-d2ec-11e7-898c-7f3dd0211624.png)

the only difference between the two is that the codemirror component was created in the watch part and now with 1.0 its under the methods part. can that explain it?

**Comment by David-Desmaisons** [comment]
It is almost impossible for me to know what it is happening here without knowing your components and the way the communicate. From what you told me, I am pretty sure that this is not linked to version 1.0.0 but to the change you made. 
Try to create the component as you were doing in od version.
Even better would be to create a vue component around the codemirror element and send information from ViewModel using a props.

**Comment by jmecosta** [comment]
Ok i will try that, it's good idea anyhow to have a new vue component for codemirror. I've tried the props thing when first upgrading but did not went far :) are there examples that I can follow that use props and viemodel? Thanks

**Comment by David-Desmaisons** [comment]
https://github.com/David-Desmaisons/Music.Cover.Finder

and

https://github.com/NeutroniumCore/CodeDependencyScanner

are good example of usage of this pattern

**Comment by jmecosta** [comment]
@David-Desmaisons great thanks. i will try those. regards
