### ISSUE TITLE
Neutronium - Info: Unable to convert javascript object

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#47]
Hi @David-Desmaisons 

i get these messages, but have no idea where those are created. Is it possible to include line number and file where this occurs? 

Neutronium - Info: Unable to convert javascript object: Neutronium.WebBrowserEngine.ChromiumFx.V8Object.ChromiumFXJavascriptObject to C# session. Value will be default to null. Please check javascript bindings.
Neutronium - Error - Unable to update ViewModel from View, exception raised: Unable to convert javascript object: Neutronium.WebBrowserEngine.ChromiumFx.V8Object.ChromiumFXJavascriptObject to C# session. Value will be default to null. Please check javascript bindings.

thanks

**Comment by jmecosta** [comment]
and a few more weird messages:

Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Info: Exception encountred during task dispatch: Object reference not set to an instance of an object.
Neutronium - Browser Log: Message: Neutronium: ViewModel injected, **source: , line number: 11183,** page: file:///D:/prod/tools/BuildTools/buildallextension/BuildDrop/vs17/farmi.html

would be nice here also to know a bit more context

**Comment by David-Desmaisons** [comment]
Hello, regarding the first message: you are calling a command with an unexpected object and in return Neutronium will call Command with null parameter. This is due to a problem in the javascript side when calling a command. The behaviour was the same in the precedent version expect it was not logged. So this message can help improve the communication between JS and C# sending correct argument.

Reagrding the second message I never seen it. Could you give more context? From the stack, I would guess this happens during the loading of the HTML page, correct? I would guess that there are some javascript errors in the scripts on page load that may cause this problem. Try to debug stopping on exception to get more information.

**Comment by jmecosta** [comment]
@David-Desmaisons yes the second ones were related to some errors in javascript side, ive decided to use c# objects in most of my bindings and then i saw you have limit implementation for those (bad idea). 

for the first warnings is still a bit weird i get the message

Neutronium - Info: Unable to convert javascript object: Neutronium.WebBrowserEngine.ChromiumFx.V8Object.ChromiumFXJavascriptObject to C# session. Value will be default to null. Please check javascript bindings.
Neutronium - Error - Unable to update ViewModel from View, exception raised: Unable to convert javascript object: Neutronium.WebBrowserEngine.ChromiumFx.V8Object.ChromiumFXJavascriptObject to C# session. Value will be default to null. Please check javascript bindings.

but the only command that is triggered:

![image](https://user-images.githubusercontent.com/1041352/33257615-7fd8d222-d35f-11e7-943f-d2ce4ac0b834.png)

contains non null value, so the warning should not be there.

from js side i have

```
this.ViewModel.RefreshConfigurations.Execute(this.ViewModel.SelectedEnvironment.BasePath);
```

**Comment by David-Desmaisons** [comment]
@jmecosta , looking better at the exception it seems that you are adding an element to collection with a none-supported javascript object (none basic or object not mapped).

**Comment by jmecosta** [comment]
At the moment there are really a lot of observablecollections with some complex types inside. So not possible from your side to improve the logging to tell is what c# object is causing this? I mean from a functionality point of view the application works

**Comment by jmecosta** [comment]
well actually found the type that causes it. 
```
    public class TSEnvironment
    {
        public string Name { get; set; }
        public string BasePath { get; set; }
    }
```

basically when changing its value in the multiselect component it get the warning. Supose this is a limitation of neutronium according to #46 ? 

from what i see the observable collection is mapped properly into the view, however the select cannot set the object in the c# side.

my html
```
                        <div class="row">
                            <multiselect :disabled="LocalFarmiData.EditorDisabled" id="environmentBoxSelectId" v-model="ViewModel.SelectedFTCEnvironment" :options="ViewModel.OptionsEnv" placeholder="Choose Environment" :close-on-select="true" :custom-label="nameWithEnv"></multiselect>
                        </div>
```

nothing special in javascript, besides the initalization

```
            ViewModel: {
                SelectedFTCEnvironment: { Name: "", BasePath: ""},
```

or am i doing something weird with all this? thanks

**Comment by David-Desmaisons** [comment]
You are correct regarding the limitation.

Regarding the initalization, well if you need it, you should do it in the C# side:

C#:
```CSharp
SelectedFTCEnvironment = new ObservableCollection<TSEnvironment>(){
 new TSEnvironment{Name ="", BasePath =""}
};
```

**Comment by jmecosta** [comment]
@David-Desmaisons thanks for the clarifiacation, i will wait for #46 it should help reducing the codebase quite a lot if this is supported. thanks
