### ISSUE TITLE
Where is a winform version?

### ISSUE THREAD

**Issue by ywxt** [NeutroniumCore/Neutronium#48]

**Comment by ywxt** [comment]
Hi,
  Can I find a winform version?I want to use databinding for winform instead of wpf.
  Sorry my english is bad.

**Comment by David-Desmaisons** [comment]
Hello @ywxt . There is no winform component. why wuld you need a winform component?

**Comment by David-Desmaisons** [comment]
Any feedback on this @ywxt ?
