### ISSUE TITLE
jquery not firing for some tabs

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#49]
@David-Desmaisons hi, i think i mention this before but i cant find the relevant conversation in any of the open issues. So apologies for the spam.

this is really weird, im trying to hook  some jquery events but it only works outside neturonium...

$(document).ready(function () {
    console.log('document ready'); // Active Tab
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        console.log('showing tab ' + e.target); // Active Tab
        console.log('showing tab ' + e.relatedTarget); // Previous Tab
    })
});

log outside neutronium
```
vue.js created
document ready
showing tab http://localhost:8080/farmi.html#MacroEditor
showing tab http://localhost:8080/farmi.html#editorAndTesId
```

log inside netronium
```
document ready
VM26:11183 Neutronium: ViewModel injected
vue.js created
```

i swear i saw once when playing around with this, some tabs event being fired. but i cant get it again.  The only difference is the order of the document ready and vue.js created method. Can that have an effect in jquery? and on to make it work?

thanks for the help,

**Comment by David-Desmaisons** [comment]
Well, you have issue on the way this solution is designed as you both rely on Vue and jquery for your initialization.
As you can not rely on the document ready event on a Vue context, you have to switch your application logic to perform the jquery logic inside the mounted method of main vue.js component.

**Comment by jmecosta** [comment]
Yep mounted method took care of the proper display of the codemirror thing.
However still the jquery hooks don't really fire. But anyway those were
only there so that the codemirror could refresh property.  so it seems I
don't need those for now.

Still I don't understand why would then this work in a normal browser and
not in neutronium.

Can you point out some documentation about vue.js and jquery and how they
react between themselves, sorry for this question is Abita out of scope of
neutronium.

**Comment by David-Desmaisons** [comment]
> Still I don't understand why would then this work in a normal browser and
> not in neutronium.
To work the code you wrote rely on document ready event, so you make the assumption that when onready is called, DOM is updated. This is not safe to make such an assumption as Vue is in charge of making DOM updates and this may happen after (see vue lifecycle hook). In case of neutronium addicional script are injected in the javascript session during HTML loading and as a consequence DOM is updated after onready.

For jquery and vue.js, see here for example:
https://vuejsdevelopers.com/2017/05/20/vue-js-safely-jquery-plugin/

**Comment by jmecosta** [comment]
Already nice first paragraph :) thanks for the pointer. I will try to avoid
using it.  Thanks
