### ISSUE TITLE
Unable to use reCAPTCHA 2

### ISSUE THREAD

**Issue by o2genum** [NeutroniumCore/Neutronium#50]
I'm thinking about using reCAPTCHA 2 in my app to prevent login brute-forcing. There are no google cookies in Neutronium, so I would show this strong captcha only for 10+ failed login attempts from a single IP.

However, reCAPTCHA 2 says "ERROR for site owner: Invalid domain for site key".

To reproduce it, just register a new reCAPTCHA "Invisible reCAPTCHA" key [here](https://www.google.com/recaptcha/admin#list), and it gives a snippet to paste into `index.html` (outside of Vue-controlled elements, to get it working with Vue is another question).

There is a similar [problem in React Native](https://stackoverflow.com/questions/45994203/react-native-with-recatpcha), and they solve it by using a _base url_.

I tried to fake `Referer:` and `Origin:` headers in requests, but it's not enough, reCAPTCHA javascript seems to check the url on client-side, too. And on client side I have `pack://` urls now.

**Comment by o2genum** [comment]
Not sure if this is solvable, though, in Electron, they seem to be [strguggling with it, too](https://github.com/electron/electron/issues/11160).

**Comment by David-Desmaisons** [comment]
Could you create a sample github project so I can take a look?

**Comment by o2genum** [comment]
I think this can be closed, I decided not to use reCAPTCHA.

reCAPTCHA seems to dislike `pack://,,,application/` urls. It wants something like `https://example.com`. Probably this may affect some other JS libraries that make this assumption about the browser environment. So [base URI](https://stackoverflow.com/questions/45994203/react-native-with-recatpcha) would still be a good feature to have, if it's possible to introduce it without too much effort.
