### ISSUE TITLE
Setting Accept-Languages (preferred web language)

### ISSUE THREAD

**Issue by o2genum** [NeutroniumCore/Neutronium#51]
This is useful for displaying web pages in pop-ups, for example.

**Comment by David-Desmaisons** [comment]
On The App.xaml.cs file try:

```
protected override void UpdateChromiumSettings(CfxSettings settings) 
 {
            settings.AcceptLanguageList = "pt,pt-br";
}
```

**Comment by David-Desmaisons** [comment]
Hello @o2genum , did this solve the issue?

**Comment by o2genum** [comment]
Ended up not using this, but it works. Nice to have a way to pass Chromium settings.
