### ISSUE TITLE
How to edit a property of an object in an ObservableCollection from Vue.js

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/Neutronium#54]
You claim two-way binding, and this seems to work fine for simple objects in the ViewModel.

However, I can't seem to get the ViewModel to reflect changes I make in Vue.js to ObservableCollections...

Do you have an example that goes beyond just creating and removing items from an ObservableCollection?

Thanks!

**Comment by David-Desmaisons** [comment]
Two-way data binding is working in Neutronium provided C# object implements INotifyPropertyChanged and INotifyCollectionChanged.
If you scenario is editing a property of an element within a collection well this element should implement INotifyPropertyChanged for the corresponding property.

[Example.ChromiumFX.Vue.Collection](https://github.com/NeutroniumCore/Neutronium/tree/master/Examples/Example.ChromiumFX.Vue.Collection), [/Example.ChromiumFX.Vue.UI](https://github.com/NeutroniumCore/Neutronium/tree/master/Examples/Example.ChromiumFX.Vue.UI)
[Neutronium.SPA.Demo](https://github.com/NeutroniumCore/Neutronium.SPA.Demo) all have this kind of bindings. You can also check the application traces to get feedabck on bindings.

If these advices/examples did not help you provide precise scenario, viewModel code, etc..

**Comment by fizxmike** [comment]
Ok... I got it to work by creating an ObservableCollection of ViewModels based on INotifyPropertyChanged which wrap the objects (actually EntityFramework Entities) I'd like to modify through Vue.js. WHAT A PAIN since that object has like 10 properties (the class is 100+ lines long including curly braces - basically copied the entity framework model definition and implemented the gets and sets for each property)! Please tell me there is an easier more elegant (DRY) way?

Maybe it would be worthwhile to think about some better entity framework support?

**Comment by fizxmike** [comment]
Oh, I did find that 2-way binding of  Nullable<int> types is not working for some reason. One way seems to work okay (ViewModel -> Vue.js) but not the other way.

Perhaps this issue turns into:
1. a feature request for native two-way Entity Framework binding support (I might be able to help code this up once I figure out a shortcut to what I had to do above... EF must be using some sort of INotifyPropertyChanged magic under the hood, how else would the DBContext track changes to entities? I'd imagine it's doable).

1. an issue regarding `Nullable<T>` two-way binding not working, for example, the message box never pops up when changing the Priority property in Vue.js:
```C#
// this is in my ViewModel, other properties get and set just fine, except this one
...
  public Nullable<int> Priority
    {
      get { return _StructureObjective.Priority; }
      set
      {
        _StructureObjective.Priority = value;
        MessageBox.Show("Bro, Priority changed.");
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Priority"));
      }
    }
...
```

**Comment by David-Desmaisons** [comment]
Well, this how standard WPF works: if you need binding you have to implement INotifyPropertyChanged, as this is the only way to tell that something has changed.

Neutronium behaves no different.

That said it is probably a good think in term of architecture that you have ViewModel distinct from Model as you can add validation in the ViewModel layer and also filter only the relevant part of information to be displayed in the UI.

> Maybe it would be worthwhile to think about some better entity framework support?
There might be some strategy of transfornation Model into viewModel based on reflection or dynamics but this exceeds by far Neutronium scope. As this is exactly the same problematic as standard WPF MVVM you can check on stackoverflow for help.

**Comment by David-Desmaisons** [comment]
@fizxmike  Could you create a dedicated issue for the Nullable binding please?

**Comment by fizxmike** [comment]
Ok, EF support being out of scope is fine with me.
