### ISSUE TITLE
Two-Way Binding does not work for Nullable<T> types.

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/Neutronium#55]
```C#
// this is in my ViewModel, other properties get and set just fine, except this one
...
    public Nullable<int> Priority
    {
      get { return _StructureObjective.Priority; }
      set
      {
        _StructureObjective.Priority = value;
        MessageBox.Show("Bro, Priority changed.");
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs("Priority"));
      }
    }
...
```

**Comment by David-Desmaisons** [comment]
The set is not working when updating from javascript with integer value or null?
Did you check the application trace when changing the priority value? It is possible that you set the priority as a string on the javascript side and in this case this won't work.

**Comment by David-Desmaisons** [comment]
@fizxmike , I just perform addicional test on nullable and I am not abble to reproduce. Please check the trace and the type of the Priority set on the JS side.

**Comment by fizxmike** [comment]
Hmm... automatic type conversion happens all the time in JavaScript, so it is a little unexpected to have to explicitly deal with type casting when assigning a value to an object... do you expose the C# type information on the JavaScript side?

Also, silent failure is undesirable.

What about attempting type conversion on all incoming (to C#) strings as an option? Or at least an option for "verbose" failures so this type of error would bubble up in testing vs. wasting time debugging and creating an issue (like this one)?

Thanks!

**Comment by David-Desmaisons** [comment]
1) There are no silent failure. This is the kind of message that are reported in such a case:

```
Info: Unable to set C# from javascript object: property: Int32 of System.Int32, javascript value ddddd. Exception System.InvalidCastException: Conversão especificada não é válida.
   em SetInt32(Object , Object )
   em Neutronium.Core.Infra.Reflection.PropertyAccessor.Set(Object target, Object value) na C:\Users\David\Documents\Source\Neutronium\Neutronium.Core\Infra\Reflection\PropertyAccessor.cs:linha 132
   em Neutronium.Core.Binding.GlueObject.AttibuteUpdater.Set(Object value) na C:\Users\David\Documents\Source\Neutronium\Neutronium.Core\Binding\GlueObject\AttibuteUpdater.cs:linha 30
```
This is Neutronium log that in debug mode uses the application trace.

2) Regarding type conversion, well you are creating a javascript viewModel to reflect the C# viewModel so by design the corresponding target type is known. Implicit type conversion may introduce subtle and hard to find bugs so no need to change it for now. "Explicit is better than implicit."
