### ISSUE TITLE
Bug: Windows Scaling breakes Chromium Renderer

### ISSUE THREAD

**Issue by genyx** [NeutroniumCore/Neutronium#56]
Set font scaling to 125%, then reboot. On Mouse Hovering the input field this happens:

![unknown](https://user-images.githubusercontent.com/17216038/34199911-86fe398a-e56f-11e7-89b5-96372a23e7ce.png)

I am not able to reproduce it on my own pc. it just appeared on my partners. Windows 10 with latest updates. Chrome is normally installed, so all the dependencies should be there. Two monitor setup: One was set at 100% the other one at 125%. Setting both back to 100% and rebooting fixed the issue.

This is not urgent in my case, but i just thought i report it.

Addition: Also note that the min-max-close controls are on the right far off screen.

**Comment by jmecosta** [comment]
hi,

this is related with #40 , it seems with latest windows updates now i get this everywhere even over RDP. Earlier this would happen only on local computer with high dpi settings. So basically,  with latest updates it just brakes rendering if using hi dpi screens?

**Comment by jmecosta** [comment]
workaround:

> 
        protected override void UpdateLineCommandArg(CfxOnBeforeCommandLineProcessingEventArgs beforeLineCommand)
        {
            beforeLineCommand.CommandLine.AppendSwitch("disable-gpu");
        }

solves for me, im not sure however what is the overall effect on WebGl apparently will have a effect. For me use d3.js and so far it works.

**Comment by TGNThump** [comment]
Where does the workaround code need to go?

**Comment by TGNThump** [comment]
I'm having similar issues. GUI scaling at 125%.
![image](https://user-images.githubusercontent.com/1783166/35918268-1e5f99b2-0c09-11e8-8023-45620a3caf32.png)

**Comment by jmecosta** [comment]
at the start of the application

[image: image.png]

**Comment by genyx** [comment]
the workaround from @jmecosta works fine. this issue can be closed, but you should update the documentation so others will know.
