### ISSUE TITLE
Question - How to call "Print" on ChromiumFX Backend?

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/Neutronium#57]
My app has a requirement that the view be saved to PDF (for record keeping purposes). What is the recommended way to do this?

**Comment by fizxmike** [comment]
solution is to do it from javascript: window.print()

**Comment by David-Desmaisons** [comment]
Thanks for documenting the solution @fizxmike . I was taking a look at CEF API and there should be a way also to display Print command in the contextual menu.
Will this be a better solution as your current one? How are you calling window.print(), in response to a button click maybe?

**Comment by fizxmike** [comment]
Actually, this is not the common "print to pdf" dialog you would expect to see (like on google chrome), instead, it's the default windows print dialog which is pretty horrible and the rendering sucks. I was hoping to use chromium's print to pdf extension functionality mentioned here:
http://magpcss.org/ceforum/viewtopic.php?f=17&t=15168

**Comment by fizxmike** [comment]
Yes, I would like to either print with on-click event, or have it in contextual menu... regardless, I don't know how to get my hooks into the chormium browser instance through neutronium, any tips? I'd figure I should be able to modify the browser instance here somewhere: https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Overview.md#htmlenginefactory

**Comment by David-Desmaisons** [comment]
This is current print dialog available througth the context menu:

![image](https://user-images.githubusercontent.com/524617/34449923-8c3cdd98-ece5-11e7-81b1-d42717f388d4.png)

**Comment by David-Desmaisons** [comment]
I am taking a look at the best way to expose this, I will let you know once I figure it out.
Maybe I will expose some additional APIs in version 1.2.0.

**Comment by fizxmike** [comment]
Thanks! This is same thing that shows up with window.print(); Basically, my complaint is the "Mircosoft Print to PDF" printer sucks... using the ChromiumFX (cfx) print extension would be the desired solution for me. Also, "printing" is not such a priority for anyone else, I happen to work in the medical field where documentation is king.

**Comment by fizxmike** [comment]
...So just exposing direct access to the ChromiumWebBrowser object and/or its settings is a more general solution.

**Comment by David-Desmaisons** [comment]
Documented here on how adding Print in contextual menu (this is possible in version 1.1.0):

https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/FAQ.md#is-it-possible-to-print-the-content-of-the-page
