### ISSUE TITLE
Intermittent Crashes on Debug VM

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/Neutronium#59]
Occasionally I get these errors showing up in the debug output and sometimes the Debug VM action crashes the browser window:
Exception thrown: 'System.IO.EndOfStreamException' in ChromiumFX.dll
Exception thrown: 'Chromium.CfxRemotingException' in ChromiumFX.dll
Exception thrown: 'System.IO.IOException' in ChromiumFX.dll

... any idea what they mean? Any way to debug or avoid them somehow? Maybe it has to do with objects with "null" values on JS side?

Note: I'm using x64 builds

**Comment by genyx** [comment]
I am getting similar exceptions and don't know where they were thrown. I am ignoring them, because the application is running normally.

**Comment by fizxmike** [comment]
I would ignore them, except sometimes my app crashes on me... this seemingly non-deterministic behavior is worrisome... I was just looking for some pointers or "known issues" to avoid this from happening.

**Comment by David-Desmaisons** [comment]
@fizxmike , basically the only CfxRemotingException I am aware of are the one described by @genyx :

When a Chromium process is getting killed, such exceptions are raised and catched in the application by ChromiumFx. It is kind of annoying but not too grave as the application is still working normally. This will tipically happen when you close a debug window.

That said, if you have the same exception giving application then share.

**Comment by fizxmike** [comment]
Once I started using NuGet package for x64 builds, the unexpected crashes stopped.
