### ISSUE TITLE
Optimize project size

### ISSUE THREAD

**Issue by genyx** [NeutroniumCore/Neutronium#64]
It would be so good, if you could optimize the files that are required by the project. I currently set up just a little program with not yet any logic or graphics or other large content. Nevertheless the repository (after npm i, nuget restore and compiling) has over 1 GB and over 120k files on the disk. I know that most of that are node_modules that are not included in the final "binary" that i can make a setup for. 

But working on so many files is hard for me and the computer. In fact i had to do `npm i` a few times, taking ages each time, but also resulting in a hard disk failure i was not able to resolve yet. ~ gonna run chkdsk over night and see if then i can *delete the node_modules folder* which he doesnt let me to do right now - windows explorer dies every time i try to delete the node_modules folder with its million of files. 

Hope you understand the problem. I really have to question if the Neutronium Framework (at least with Vue.js!) is suitable for my company.

**Comment by fizxmike** [comment]
Welcome to "modern" iron-clad package management. The assumption is that disk space is cheep, and managing package dependencies by hand is expensive, and broken dependencies must be avoided AT ALL COSTS!! say you want to use package A (which relies on package B version 1) and package C (which relies on the same package B but version 2)... with traditional package management, you couldn't do that. But with modern package management (like what npm does) you CAN do that, moreover, you don't need to manage it by hand. This isolation inevitably creates a monster of files in your packages folder. See here for more details: https://lexi-lambda.github.io/blog/2016/08/24/understanding-the-npm-dependency-model/

As for your hard disk problem... i recommend either getting an SSD replacement, or use a tool like SpinRite to keep it in tip top shape... but all storage media fails eventually, expect that and mitigate.
https://www.grc.com/sr/spinrite.htm

**Comment by David-Desmaisons** [comment]
Hello @genyx , well as you mentioned this is a generic issue linked to modern web devellopement in general and node_modules in particular, and vue framework is not differenrt from the others compitetors. There is not so much that I can do on my side. 
I made some test for a simple application node_modules size is up to 354 MB. That said javascript file built by webpack and the only needed to be shipped with the application was 665kb.
Which version of npm are you using? I switch to version 5 (5.5.1) recently and there was hughe performance improvement.

**Comment by David-Desmaisons** [comment]
I am closing this one. Project size is linked to modern web develop tools and there nothing I can do. That said Neutronium can be used without webpack reducing project size on disk, but without the power of these tools.
