### ISSUE TITLE
"cmd(true)" parsing error in vm.cjson

### ISSUE THREAD

**Issue by fizxmike** [NeutroniumCore/Neutronium#65]
I noticed this new addition after using latest nuget repo (with x64 support!). I see it is a placeholder for ICommands in ViewModel... but I get a parsing error when running in `npm run dev` mode now...

Do I need to update some JS file in my webpack config somehow to make it work properly?

**Comment by David-Desmaisons** [comment]
Exact:
Update (or use) neutronium-vm-loader to version 1.3.0.
See [guide here].( https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Migrate_from_1_1_to_version_1_2.md)

**Comment by David-Desmaisons** [comment]
@fizxmike Were you abble to solve the issue using the guideline?

**Comment by fizxmike** [comment]
Not yet. But you can close this issue if you want. Otherwise I will close it once I verify your guide works.

**Comment by fizxmike** [comment]
Looks like code for "vueInstanceOption" is missing in this migration guide? (I use Vue-Router and used that function to set it up.
