### ISSUE TITLE
Displaying/Embedding a Web Page

### ISSUE THREAD

**Issue by krconv** [NeutroniumCore/Neutronium#66]
Is there any way to embed a webpage in a a fully Neutronium application? Electron has a [`<webview>`](https://electronjs.org/docs/api/webview-tag) tag which seems to be able to support just this; is there an equivalent that is possible here?

**Comment by David-Desmaisons** [comment]
Well, you can use an <iframe>:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by krconv** [comment]
Is there a solution that is able to embed any web page? I've tried to disable the `<iframe>` security in Chrome but couldn't find anything; would be awesome if somehow it was possible to embed webpages in a Neutronium view in the same way that a webpage could be embedded in C# native view with a browser.

**Comment by David-Desmaisons** [comment]
@krconv , with Neutronium you have access to [all CEF API](https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Accessing_Chromium_API.md) so it should be possible to desactivate iframe security.

That said I am curious of your scenario: Neutronium is meant to be an UI framework based on HTML not a library providing an WebBrowser control. If you are looking for the second then CefSharp may be the bast option. In any case I am interested in knowing what is your use case.

**Comment by krconv** [comment]
Thanks for the link; I'll look into the CEF forum to see if there is someway to accomplish that; found [some suggestions](http://magpcss.org/ceforum/viewtopic.php?f=6&t=14379) right off the bat that seem helpful.

I'm building an application which tracks a user's eye movement (using external hardware, which is why I'm using C#) while the user browses a website. I am really loving being able to build the view with VueJS. The problem is while where I was embedding web content inside native code, now I need to embed web content inside web content inside native code.
