### ISSUE TITLE
Application not rendering in Release mode, plus System.ObjectDisposedException

### ISSUE THREAD

**Issue by TGNThump** [NeutroniumCore/Neutronium#73]
When running in Release mode (after running npm run build), Neutronium displays an empty window, and then produces the following error on closing the window:
```
System.ObjectDisposedException occurred
  HResult=0x80131622
  Message=Cannot access a disposed object.
Object name: 'CfrApp'.
  Source=ChromiumFX
  StackTrace:
   at Chromium.Remote.CfrObject.get_RemotePtr()
   at Chromium.Remote.CfrApp..ctor()
   at Chromium.WebBrowser.RenderProcess..ctor()
   at Chromium.WebBrowser.RenderProcess.RenderProcessMain()
   at Chromium.Remote.ExecuteProcessRemoteCall.ExecuteInTargetProcess(RemoteConnection connection)
   at Chromium.Remote.RemoteCall.ExecutionThreadEntry(RemoteConnection connection)
   at Chromium.Remote.RemoteCall.<>c__DisplayClass12_0.<ReadRequest>b__1()
   at Chromium.Remote.WorkerPool.Pool()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

Running npm build integrated and then running the project in Debug mode with `-dev` works fine.

**Comment by David-Desmaisons** [comment]
Hello @TGNThump , Thanks for reporting the issue. 
Which version of Neutronium are you using? 
Is it installed using the VS template?
Is it linked to a specific view or always happening?
When you mention release mode, is it a release build or debug build runt in ApplicationMode.Production?

Thanks

**Comment by TGNThump** [comment]
```
Neutronium.Core 1.3.0
Neutronium.WPF 1.3.0
Chromium 56.0.2924.76
Platform x64
Vue.js 2.5.13
Browser ChromiumFX
Binding VueInjectorV2
```
Neutronium 1.3 installed via the VS template. I only have one view, so I can't say if its linked or always. The issue arises with a release build (application mode set to production)

**Comment by genyx** [comment]
Make sure you disable „prefer 32 bit“ as mentioned here: https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Migrate_from_1_1_to_version_1_2.md

**Comment by TGNThump** [comment]
Disabling the prefer 32 bit checkbox for the release configuration fixed the error message on close, but the chromium container still displays a blank white window while not running `npm run integrated` and using `-dev` on either build config.

The content of the View/Main folder (excluding node_modules) is included in the project and the View/Main/dist folder items are all set as Content / Copy always.

**Comment by TGNThump** [comment]
Getting the following console errors in dev tools (Inspecting the blank neutronium window):
![image](https://user-images.githubusercontent.com/1783166/36382542-2e8ed2f4-1581-11e8-9d0e-64e97094a6e5.png)

**Comment by David-Desmaisons** [comment]
From the first warning, it seems that some alterations have been done in the View\main\dist\index.HTML so that the main div can not be found. Make sure it is unaltered:

```HTML
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>main</title>
  <link rel="stylesheet" type="text/css" href="./styles.css">
</head>

<body>
  <div id="main" style="height: 100%;overflow: hidden;">
  </div>
  <script src="./build.js"></script>
</body>

</html>
```

**Comment by TGNThump** [comment]
Yup, matches exactly.

**Comment by David-Desmaisons** [comment]
View/Main/dist folder items should be `Resource/ Dot not Copy.`

**Comment by TGNThump** [comment]
Thanks, both Release and Debug builds are now working. I still cant publish though, after building for pubish, the installer / .application file throws the following error:
```
+ Reference in the manifest does not match the identity of the downloaded assembly ChromiumFXRenderProcess.exe.
```

**Comment by David-Desmaisons** [comment]
Please open a dedicated issue, inked to click-once deploy.
