### ISSUE TITLE
Click-once deploy installer fails

### ISSUE THREAD

**Issue by TGNThump** [NeutroniumCore/Neutronium#74]
Click-once deploy installer fails with the following error:
```
+ Reference in the manifest does not match the identity of the downloaded assembly ChromiumFXRenderProcess.exe.
```

**Comment by fizxmike** [comment]
Same experience.

**Comment by David-Desmaisons** [comment]
I am investigating this one. From what I got from now, I might need to publish new nugets packages.

**Comment by David-Desmaisons** [comment]
Corrected in Neutronium.Chromiumfx.Vue version 1.3.1
