### ISSUE TITLE
Are you guys doing the same?

### ISSUE THREAD

**Issue by seriouz** [NeutroniumCore/Neutronium#76]
Do you know the Chromely project?

https://github.com/mattkol/Chromely

It seems you guys are doing pretty much the same?

**Comment by David-Desmaisons** [comment]
@seriouz Thanks for pointing out this repository I was not aware of.

Main differences of the projects:

- Neutronium is currently only WPF
- Neutronium is an abstraction on top of webBrowser allowing MVVM binding with C# ViewModel
- Chromely supports Windows and Linux
- Chromely bindings with C# are simplier.

That said, as mentioned by @mattkol in issue #58 and issue #75 ,  it should be possible for Neutronium to use Chromely as an infrastructure and allow linux support.

I will definetivelly study this possibility.
