### ISSUE TITLE
How does it exactly bind

### ISSUE THREAD

**Issue by enemyofthedawn** [NeutroniumCore/Neutronium#77]
It uses vue.js somehow, does it convert C# viewmodel to vue.js bindings somehow under the hood?

Does it mean you don't need to write any javascript? just like WPF with HTML and CSS instead of XAML?

For example in XAML you do something like `<Label Content={Binding PropertyName} />` how is this binding performed in HTML. I can't understand.

It somehow generates javascript run-time and executes it so the HTML can be updated?

> Use standard javascript frameworks to build UI

But using Vue.js means writing logic in Javascript/Typescript. So how you glue C# to it.

**Comment by David-Desmaisons** [comment]
@enemyofthedawn , you can find some information on how Neutronium works:
https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Architecture.md
https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/How_it_works.md

>  just like WPF with HTML and CSS instead of XAML?
Exactly! This is Neutronium philosophy.

> Does it mean you don't need to write any javascript?
You don't need any javascript to bridge your data beetween javascript and C#.
Of course, you will need javascript for your Vue components.

Under the hood it uses reflection to transform C# ViewModel into javascript object pass it to the browser session that uses it as Vue props.
Neutronium also adds listeners to ViewModel on both C# and javascript side to handle two-way bindings.

>  So how you glue C# to it.
ViewModel converted from C# is passed as props to Vue instance. That's it.

See examples:
https://github.com/David-Desmaisons/Music.Cover.Finder
https://github.com/NeutroniumCore/CodeDependencyScanner

**Comment by enemyofthedawn** [comment]
Thanks
