### ISSUE TITLE
How to fire some javascript code from the c# side

### ISSUE THREAD

**Issue by jmecosta** [NeutroniumCore/Neutronium#8]
hi @David-Desmaisons 

trying to have my application detecting some change in the view, after the view model has changed its state. tried a simple <input> without any bindings to the view model. it gets triggered outside the neutronium application however it does not when running inside it.

Is this expected?

What i want basically is to fire some javascript code from the c# side, so that i don't need to have so many bindings between the view and the model. So be good to have some logic in the client side.

Can that be done? thanks

regards
Jorge Costa

**Comment by David-Desmaisons** [comment]
Hello @jmecosta , 
in Neutronium all comunication between C# and javascript is done via View Model binding.
If you need to execute a javascript function trigerred in C#, the best way to do this is to use a property in a viewmodel and react when its value changed:


C# ViewModel:
```C#
public Data Data
{
    get {return _data;}
   set { _data=value; FirePropertyChanged(nameof(Data));}
}
```

Vue Vm:
```javascript
   watch:{
       Data(newValue){
            //run the javascript function here
            executeCb(newValue);
       }
   }
```

To run the javascript function just do in your C# code:
```C#
vm.Data = data;
```

**Comment by jmecosta** [comment]
wow, how cool is that? Simple and clean. Great. thanks for the help. works great.
