### ISSUE TITLE
Click Once Publication problems and proj

### ISSUE THREAD

**Issue by klauth86** [NeutroniumCore/Neutronium#80]
Hi!

I also notice some problems with publication app from WPF Vue.js template.
1) First of all publish build crashes and **I found out that it can be fixed by placing addon dependencies in this order**
- Unofficial.Cef.for.Chromiumfx.x64.3.2924.1\build\Unofficial.Cef.for.Chromiumfx.x64.targets
- Unofficial.Cef.for.Chromiumfx.x86.3.2924.1\build\Unofficial.Cef.for.Chromiumfx.x86.targets
- Unofficial.Chromiumfx.3.2924.5\build\Unofficial.Chromiumfx.targets
- Neutronium.WebBrowserEngine.ChromiumFx.1.3.0\build\Neutronium.WebBrowserEngine.ChromiumFx.props
- Neutronium.JavascriptFramework.Vue.1.3.0\build\Neutronium.JavascriptFramework.Vue.props
- Unofficial.Chromiumfx.3.2924.5\build\Unofficial.Chromiumfx.props

2) Ok, we have our publish build ended successfully. But now we have problems with installing in the sence of manifest verification. Although from NuGet app the manifest get version 1.3.0.0 of ChromiumFXRenderProcess, after publishing ChromiumFXRenderProcess.exe get default manifest with 1.0.0.0 version and this causes error. **As for the solution - just change ChromiumFXRenderProcess proj props NOT to generate manifest**

3) I dont know how ti fix it (maybe use macros), but at the moment template use only one "../" in libs paths, regardless of real level of proj in solution

IMPORTANT NOTE: we publish from console with MSBUILD

**Comment by David-Desmaisons** [comment]
What is the version of Neutronium, you are trying to publish?
Older version of Neutronium have issues with Click-once that were corrected in version 1.3.1, please check with this version.
As reference creating a project from template and publishing with click-once will work.

**Comment by klauth86** [comment]
Okay, I try 1.3.1 and move to this version, thanx ))

**Comment by klauth86** [comment]
@David-Desmaisons 
Just check on 1.3.1, Click Once Publication succeed.
