### ISSUE TITLE
Markup change doesn't  reflects

### ISSUE THREAD

**Issue by hard-rox** [NeutroniumCore/Neutronium#84]
I created a Neutronium Vue App in visual studio. When I run it It works fine but after i changes some markups in App.vue file and run it. App runs successfully but the changes is not reflects. The view remains same. Would you please help me out?

My changes in App.vue file.
![image](https://user-images.githubusercontent.com/20935652/42410389-bc9cac38-820a-11e8-8abd-f5deef40e5e6.png)

When I run my app.
![image](https://user-images.githubusercontent.com/20935652/42410436-4d2eebb2-820b-11e8-9f70-173db08b9f7f.png)

**Comment by fizxmike** [comment]
After you edit, you need to run `npm run build` in views/main folder, then rebuild C# project.

**Comment by hard-rox** [comment]
@fizxmike Thanks for your reply. Would you please provide a better and detailed documentation on Nutronium?

**Comment by David-Desmaisons** [comment]
Hello @hard-rox , here is the corresponding documentation:
https://github.com/NeutroniumCore/Neutronium/blob/master/Documentation/Content/Build_large_project_with_Vue.js_and_Webpack.md

**Comment by hard-rox** [comment]
@David-Desmaisons  Thanks for your attention. I am closing the issue now.
