### ISSUE TITLE
Running 'npm run build' does not generate index.html in dist folder

### ISSUE THREAD

**Issue by osum4est** [NeutroniumCore/Neutronium#85]
As the title says, running 'npm run build' does not generate index.html (or any other html files for that matter). This is a problem because the visual studio template looks for dist/index.html. I could of course change it to look in the base folder, I'm just not sure if that was intended.

**Comment by David-Desmaisons** [comment]
Could you specify your scenario please? When using neutronium-vue template, a index.html with boilerplate is created, you only have to make sure it is included in the visual studio project and everything will work fine.
