### ISSUE TITLE
Angular Binding version

### ISSUE THREAD

**Issue by Franki1986** [NeutroniumCore/Neutronium#86]
Hello,

I found your project while searching for a lightweight version of electron. For now it looks like my final decision. But I am developing in angular 6. Is there the possibilty to get a binding version for it? At the end, the vue and angular syntax is very similar.

**Comment by David-Desmaisons** [comment]
Hello @Franki1986,

This is not part of my current plans as angular is very opinionated so it is hard to make it work with other  workflow.
That said Neutronium is now working fine with Mobx , and I know that there was some integration between Mobx and Angular.
This could be the way to go, but it will not be my priority.

**Comment by Franki1986** [comment]
Ok, thanks for your response! I will have a look at this...
