### ISSUE TITLE
Chromium doesnt allows Cross-Origin-Request

### ISSUE THREAD

**Issue by reinerBa** [NeutroniumCore/Neutronium#9]
Hallo,
i tried to use the library to make a request with javascript but chromium prevents my Request. 

`XMLHttpRequest cannot load https://WEBSITE.net/echo/negotiate?clientProtocol=1.5&_=1481228307020. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.`

For a simillar reason i wasnt able to get the Dom inside of an iframe. In CefSharp it seems to be deactivated and with a setting this seems to be possible like:

`chromium-browser --disable-web-security --user-data-dir`
[http://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome](url)

Neutronium is very convenient compact so where can i deactivate this restriction in my chromium app?
thanks in regards

**Comment by David-Desmaisons** [comment]
Hello @reinerBa , you can override ChromiumFxWebBrowserApp UpdateLineCommandArg method to add argument line switch to chromium process.
This method receives a CfxOnBeforeCommandLineProcessingEventArgs object, see [here](http://chromiumfx.bitbucket.org/api/html/T_Chromium_Event_CfxOnBeforeCommandLineProcessingEventArgs.htm) for reference.

```C#
protected override void UpdateLineCommandArg(CfxOnBeforeCommandLineProcessingEventArgs 
beforeLineCommand)
{
    beforeLineCommand.CommandLine.AppendSwitch("disable-web-security");
}
```


See example solution [/Example.ChromiumFX.Vue.SOP](https://github.com/NeutroniumCore/Neutronium/tree/master/Examples/Example.ChromiumFX.Vue.SOP) for complete example

**Comment by reinerBa** [comment]
Works great, thank you very much for the fast answer and the great Example :)
