### ISSUE TITLE
Splash screen Support

### ISSUE THREAD

**Issue by simonbuehler** [NeutroniumCore/Neutronium#92]
hi,

great project, props for your work!
Is there a way to have splash screen like a custom sized frameless windows showing some html5 (threejs) animation? What would be best practice for such a case?

**Comment by David-Desmaisons** [comment]
Hello @simonbuehler , Thanks for your world!
This is totally possible to display some kind of splash screen during the application load.
My recomendation for this would be to use vue navigation and to have as first entry the splash screen view. As your application is ready, you will navigate to the first page.
