### ISSUE TITLE
How to change some properties of view model from C#?

### ISSUE THREAD

**Issue by HADB** [NeutroniumCore/Neutronium#99]
I want to change some properties from C# side while vue side watching these properties.
But I don't know how to get the instance of the view model to change. 
I can't find any docs or examples of this.
Want some help, Thanks!

PS: I'm using the latest v1.5.0.

**Comment by David-Desmaisons** [comment]
Hello @HADB , this question will be best suited on [Neutronium.SPA.Demo](https://github.com/NeutroniumCore/Neutronium.SPA.Demo) repo as its is an how-to question linked to this particular template, if I follow you correctly.
I would say use strategy as a standard Wpf application: use a repository to persist and share data, use depency injection  and singleton pattern to share state, etc..

**Comment by HADB** [comment]
Thanks a lot!

I finally changed the properties in `MainWindow.xaml.cs` with vue side watching the changes successfully by using the following code:

```
_ApplicationViewModelBuilder.ApplicationViewModel.ApplicationInformation.MyData = myData;
```
